Igalia/cog

- CMakeLists.txt
This ensures that CMake passes any compiler and linker flags which might be needed to ensure that a shared object can be loaded with `dlopen()`. Note that using `MODULE` results in shared objects which do not include a version string in their name. This is fine, as in the future we may want to store platform modules in a separate directort which does contain the platform API version string (e.g. `/usr/lib/cog-0.1/`)
> CMake: Use add_library(foo MODULE ...) for plug-ins

- cog.c
This fixes the following warning:
```
In file included from /usr/include/glib-2.0/glib.h:62,
from ../core/cog-webkit-utils.h:19,
from ../core/cog.h:15,
from ../cog.c:12:
../cog.c: In function ‘platform_setup’:
../cog.c:238:18: warning: format ‘%s’ expects a matching ‘char *’ argument [-Wformat=]
g_debug ("%s: Platform plugin: %s", platform_soname);
^~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmessages.h:345:32: note: in definition of macro ‘g_debug’
__VA_ARGS__)
^~~~~~~~~~~
```
-----
We really ought to build with `-Wall` as per #7... This slipped from PR #5 as there were two instances of this issue, but I fixed only one before merging it. If our build would be using `-Wall` by default I would have caught this one as well.
> Add missing __func__ parameter to g_debug() call

- cog.c
- core/cog-webkit-utils.c
- core/cog-webkit-utils.h
Instead use `WebKitWebView::web-process-terminated`, which provides additional information about the reason of the process termination. The termination reason is used to format the messages and error pages, but other than that the behaviour of the updated code remains the same.
Fixes #3
> Do not use the WebKitWebView::web-process-crashed signal

- cog.c
This fixes a bug where platform_name() was beeing returning TRUE when
no platform_name is defined. Causing it to assert on the calls to
on_create_web_view() -> cog_platform_get_view_backend()
> return FALSE early if platform_name is null in platform_setup() (#9)

- core/cog-webkit-utils.c
This situation is easily triggered by loading an URL pointing directly to a video, due to WebKit passing the responsibility of fetching data to GStreamer. In that case, do not show an error page and return `FALSE` in order to let WebKit continue with its fall-back handling, which will let the plug-in or media engine do the loading.
Fixes #2
> Skip error page when WebKit hands load to plug-in or media engine

- cogctl.c
When a non-existent command name was passed to `cmd_find_by_name()` the program would crash due to attempting to compare the command name with the `NULL` string from the terminating entry of the commands table.
This fixes the issue by making the loop do a `NULL`-check for termination instead of iterating over the number of entries in the table (which included the terminating entry).
> cogctl: Do not segfault on unrecognized command names

- CMakeLists.txt
- platform/cog-platform-fdo.c
Since we render the exported buffer to the full size of the surface, we don't need to blit it.
This patch creates a wl_buffer that wraps the buffer resource and attach it to the wayland compositor surface for rendering, thus avoiding texture mapping and GLES altogether.
Tested in Intel/i965 and i.MX6 platforms, in both cases with a noticeable increase in performance.
> Wrap and submit the exported buffer forward instead of blitting

- platform/cog-platform-fdo.c
Instead of tracking the current zoom level in the `wpe_view_data` struct, query the current zoom level from the Web view. The `.zoom_level` member of the struct, which was being left uninitialized, is unneeded and therefore removed.
> fdo: Fix adjusting the zoom level with Ctrl+{-,+}

- cog.c
- core/cog-launcher.c
- core/cog-launcher.h
- core/cog-utils.c
- core/cog-utils.h
This adds code to introspect properties of a given `GObjectClass` and obtain a set of `GOptionEntry` instances which, when added to a `GOptionGroup`, will set the values of the properties from the parsed command line options.
Then, the above utility code is used to expose the properties from `WebKitSettings` in a generic way, instead of having to manually add a `GOptionEntry` and handling for each settings.
The following CLI options are replaced by the new functionality, which covers the corresponding settings:
| Old | New |
|-----|-----|
| `--webgl` | `--enable-webgl=1` |
| `-D` <br> `--dev-tools` | `--enable-developer-extras=1` |
| `-v` <br> `--log-console` | `--enable-write-console-messages-to-stdout=1` |
Closes #27
> Provide command line options for WebKitSettings properties

- cog.c
- core/cog-launcher.c
- core/cog-launcher.h
- core/cog-utils.h
This adds a new `GOptionGroup` which will contain all the cookies-related command line flags.
Some reorganization was needed to allow early creation of the `WebKitWebContext` instance, which we need at the time when the option group is added to the `GApplication` in order to pass the context's `WebKitCookieManager` to the callback used to parse the command line.
Closes #31
> Add CLI flags for setting cookie handling options

- CMakeLists.txt
- core/cog-config.h.in
- platform/cog-platform-fdo.c
Specifically, cog needs these patches to build on a Yocto Krogoth system for i.MX6 with an slightly old version of the NXP BSP.
> Support building cog on older versions of wayland

- core/cog-launcher.c
Without this patch, compilation fails with glibc 2.23 and gcc 5.3.
Apparently older versions of glibc need stdlib.h to define EXIT_SUCCESS.
> Include stdlib.h for EXIT_SUCCESS

- platform/cog-platform-fdo.c
Most wayland compositors will offer XDG shell, but not all. We need to consider wl_shell as well.
> fdo: Handling of fullscreen env-var should not assume XDG shell

- core/cog-utils.h
- core/cogcore.pc.in
These two issues were detected by trying to use libcogcore in a C++ standalone program. There are probably more changes needed (e.g, issue https://github.com/Igalia/cog/issues/46), but these two are basic fixes to make anything build.
> A couple of fixes to libcogcore

- core/cog-platform.c
- core/cog-platform.h
- platform/cog-platform-fdo.c
This improves the FDO platform plug-in by:
- Making the `init_*` functions return errors, which get bubbled up from `cog_platform_setup()`. This includes more informative error strings, plus fetching and reporting EGL errors as well.
- The added error handling alone removes many assertions, which is quite a good improvement when it comes to knowing what went South during initialization. Also this means that other fallbacks can be used on failure (e.g. a Wayland compositor is not available), instead of  aborting the process miserably with an assertion message.
- The `clear_egl()`, `destroy_window()`, and `clear_input()` functions are made idempotent, and safe to use on partially initialized data. This allows using them to free resources at different stages of initialization in the event of …
> fdo: Introduce error handling, cleanups, and GLib assertions

- CMakeLists.txt
- README.md
This adds a new `COG_BUILD_PROGRAMS` option to CMake, enabled by default, which allows disabling building the `cog` and `cogctl` programs. This can be useful for packagers which are only interested in using the `libcogcore` library.
> CMake: Allow disabling the programs at build time

- core/cog-gtk-utils.c
Use `cog_launcher_get_shell()` + `cog_shell_get_web_view()` instead of the `cog_launcher_get_web_view()` function, which was removed.
> core: Fix building with WebKitGTK+ after CogShell introduction

- cog.c
- core/cog-shell.c
- core/cog-shell.h
The default value for the property was `NULL`, which caused a critical warning to be logged if it was not set to some value. At the same time, setting a value would cause the URI to be loaded right away after the Web view was created, which would add it to the back-forward navigation list. Some applications may prefer to not have any entry pre-added to the back-forward list, and anyway it's easy to just connect to the `CogShell::create-view` signal (or chain up if subclassing) and do the load there, so removing the property seems to be the best course of action.
----
This is an alternative take on #53
> core: Remove the CogShell::home-uri property

- core/cog-platform.c
- core/cog-platform.h
- platform/cog-platform-fdo.c
> fdo: Explicitly set the backend implementation name

- core/cog-utils.h
Starting from 2.58.0 GLib already includes the definition needed to use `g_autoptr(GEnumClass)`.
> Make it possible to build against GLib 2.58 and newer

- dbus/policy.conf.in
This patch fixes controlling Cog via dbus.
> Rename DY_DEFAULT_APPID to COG_DEFAULT_APPID and com.igalia.Dinghy1 to com.igalia.Cog1

- platform/cog-platform-fdo.c
Hold off instructing the exportable object to release the exported EGLImage
until the wl_buffer wrapping that EGLImage is released by the Wayland
compositor.
> Release the wrapped EGLImage upon wl_buffer release

- platform/cog-platform-fdo.c
With these two patches Cog launcher starts OK using wpewebkit 2.22.2 and backend-fdo on iMX8M-evk v4.9 based BSP release. I notice weston-simple-egl has a similar guard on egl_window resize and also calls wl_surface_commit when using zxdg_surface_v6.
> Cog fixes for iMX8M-evk

- platform/cog-platform-fdo.c
Certain Wayland events cause `libwpe` functions to be used, many of which need a valid WPE view backend available. To avoid trying to use a `NULL` view backend, this moves the creation of the `GSource` which integrates Wayland event dispatch with the GLib main loop to be done always after the first view backend is created.
This fixes a crash which was possible to trigger in the short window of time between using `cog_platform_setup()` and `cog_platform_get_view_backend()` by producing using input (e.g. pointer, key, or touch events) during the time window.
> Create Wayland event source after the WPE view backend

- platform/cog-platform-fdo.c
Setting the Wayland surface opaque region in fullscreen allows the compositor to
optimize the redrawing of content.
> cog-platform-fdo: Opaque region support

- core/cog-utils.c
> utils: Sort web-settings options by name

- cog.c
- core/cog-launcher.c
- core/cog-launcher.h
- core/cog-shell.c
This adds the following API function:
* cog_launcher_add_web_permissions_option_entries
Currently only 2 values are accepted 'all' and 'none', by default
no permissions are granted.
Long term, we will be able to add a more complete synthax to let the
user decide what to accept and what not.
> Add an option to control permission requests

- CMakeLists.txt
```cog --version``` of cog-0.2.0 was reporting Version 0.1.0
> Fix Project Version number

- platform/cog-platform-fdo.c
Enables Wayland HiDPI support. Also scale pointer
events by scale factor to match display. Closes #16.
Requires libwpe 1.3.0 and WebKit built with this patch - 
https://bugs.webkit.org/attachment.cgi?id=369667&action=diff
> HiDPI support

- platform/cog-platform-fdo.c
As elsewhere in the WPE stack, we should revert to using the default GLib priority.
> fdo: use the default priority for the wl_source.

- cmake/FindWaylandProtocols.cmake
Ninja will create itself the directories needed by the output files for targets, but Make does not do that, nor does the CMake Makefiles generator. Therefore, this adds a call to CMake's `make_directory` tool to ensure that the output directory will always be available, regardless of the build system being used.
Fixes #99
> CMake: Make custom commands create directories

- CMakeLists.txt
- platform/cog-platform-fdo.c
The EGLImageKHR API is scheduled for deprecation in WPEWebKit 2.26.
> fdo: Port to the new wpe_fdo_egl_exported_image API

- cog.c
- core/cog-directory-files-handler.c
- core/cog-platform.c
- core/cog-webkit-utils.c
- platform/cog-platform-fdo.c
g_assert_nonnull() and others are meant for use only with tests.
These assertions are unnafected by G_DISABLE_ASSERT so they cannot
be disabled. Replace calls to test-related assertions with g_assert().
> Replace testing-related assertions with g_assert()

- cog.c
- core/cog-directory-files-handler.c
- core/cog-platform.c
- core/cog-webkit-utils.c
- platform/cog-platform-fdo.c
Most of the asserts cleaned up in 619f8f3 ("Replace testing-related
assertions with g_assert()") were done incorrectly with an inverted
check; g_assert_nonnull(foo) should be replaced with g_assert(foo) and
g_assert_null(foo) should map to g_assert(!foo).
> Fix assertions

- platform/cog-platform-fdo.c
fix syntax error introduce in `fdo: Use device scale API only when
available in libwpe` (git show 86ba95ba)
```
error: ... platform/cog-platform-fdo.c:478:5: error: expected '}' before 'else'
else if (strcmp (interface, wl_output_interface.name) == 0) {
```
> fix syntax error in Use device scale API only when available in libwpe

- platform/cog-platform-fdo.c
The pointer_on_axis callback can receive a floating-point value that
represents the current vector distance of movement along that axis.
Current libwpe API cannot accomodate that value, so instead we should
only take the sign of that value and accordingly pass -1 or 1 as the
scrolling value for the axis event.
> pointer_on_axis: fix the axis-scrolling issues

- cog.c
Add a `--device-scale` command line option which sets the initial scaling factor for the output device. This is different from zooming the Web content with `--scale`, and is directly related to the pixel density of the display, where a scaling factor of 1.0 corresponds to the traditional the de-facto standard 96 DPI pixel density used by most computer displays. If the DPI for a display is known, it can be divided by 96 to find out a suitable device scaling factor for it.
Note that this sets only an initial value for the output device scale: a platform plug-in can change this factor later on by itself. For example the FDO platform plug-in will update it whenever the Wayland compositor reports a change of output device.
> cog: Add --device-scale command line option

- CMakeLists.txt
- core/cog-launcher.c
- core/cog-shell.c
- core/cog-utils.c
This also fixes some warnings that existed. The only tricky one was to
do with g_autoptr. I'm not sure why, but I had to hoist and initialize
this further up the scope to stop GCC complaining about it being
potentially uninitialized in _GLIB_AUTOPTR_CLEAR_FUNC_NAME.
> enable -Wall option when supported

- cog.c
This makes `cog --version` include between parentheses which WebKit port it was built for (`WPE WebKit`, or `WebKitGTK`) and its version.
----
Follow-up to #116 :wink:
> cog: Make --version also show WebKit versions

- .travis.yml
This would run also on PRs and branches. It is an alternative to #113 which IMO integrates better with GitHub. The only detail missing (which would be just a bonus feature) is to tell Travis to cache the toolchain file if it has not changed in the server, but I think we could do that in a separate PR.
> CI: Add .travis.yml to enable continuous integration

- core/cog-launcher.c
Catch the SIGINT and SIGTERM signals through g_unix_signal_add() and
cause the GApplication to quit, enabling the application to properly
clean up and dispose all of the resources.
> Handle SIGINT, SIGTERM signals gracefully

- CMakeLists.txt
- platform/cog-platform-fdo.c
The xdg-shell interface is stable and xdg-shell-v6 is deprecated.
> cog-platform-fdo: Use xdg-shell instead of xdg-shell-v6

- .travis.yml
This instructs Travis-CI to cache the contents of the `~/toolchain/` directory.  The `install` step is modified to use of `curl --time-cond` passing `~/toolchain/.installed` as the time reference, which makes curl use the `If-Modified-Since` HTTP header to avoid re-downloading the toolchain installer if the already installed toolchain (from the cache) is as new as the installer file hosted by the server.
> CI: Cache toolchain instead of always downloading it

- CMakeLists.txt
- core/cog-launcher.c
- platform/cog-platform-drm.c
Add the `drm-experimental` platform plugin that enables importing the
WPE-exported dmabuf objects into DRM FB objects and posts them to the
display through the DRM/KMS APIs.
The plugin for now avoids any possibility of mode configuration by
simply using the largest available mode and sizes the WPE instance
accordingly.
No input is yet supported. This will be added later by integrating
libinput functionality.
> Add initial DRM platform plugin support

- cog.c
The following build error was happening:
```
cog.c:18:52: error: missing binary operator before token "("
#if defined(WPE_CHECK_VERSION) && WPE_CHECK_VERSION(1, 3, 0)
```
> Fix build with -DCOG_USE_WEBKITGTK=ON

- .travis.yml
This adds a new build to the CI configuration matrix which will use Cog's WebKitGTK mode (instead of WPE) in release mode. A few shell conditionals are used to avoid the toolchain download in this case,
in favor of a native build using the WebKitGTK distribution package. The build matrix had to be expanded manually in order to allow installation of different package sets using `addons.apt` depending on the build job.
----
Having this merged will prevent accidentally breaking the WebKitGTK build mode, which then needs someone to notice and come up with fixes, for example this happened with #127 recently.
The approach used to expand the `addons.apt` variable for each build jobs was found in https://github.com/travis-ci/travis-ci/issues/3505
> CI: Add WebKitGTK build to the matrix

- core/cog-launcher.c
This reverts commit ec69b2aaf9f60c7a3df118f738681e5bc428a00b.
Because this revert was never verified.
> Revert "Revert "Handle SIGINT, SIGTERM signals gracefully (#122)""

- core/cog-shell.c
Deallocate the string used as shell name in the `cog_shell_dispose()` method to avoid leaking it.
> cog-shell: Do not leak the name property string

- core/cog-shell.c
This is needed to ensure that `g_get_prgname()` is used as fallback name when instantiation is done through `g_object_new()` and the value of the property is not explicitly set to a non-`NULL` value.
Without this fix, the `g_get_prgname()` fallback would be only applied when instantiation is done using `cog_shell_new()`.
> cog-shell: Apply g_get_prgname() fallback in _init method

- CMakeLists.txt
- core/cog-shell.c
Using `g_object_notify_by_pspec()` instead of `g_object_notify()` is preferred in the implementation of GObject classes because it avoids the lookup of the property given its string.
> cog-shell: Use g_object_notify_by_pspec()

- platform/cog-platform-drm.c
Add support for displaying wl_resource exports, first importing those objects
into gbm via GBM_BO_IMPORT_WL_BUFFER functionality and continuing with gbm_bo.
The DRM update is now moved into a standalone helper function and extended to
allow falling back to using drmModeAddFB2 if the with-modifiers import failed.
> drm-platform: support wl_resource exports, drmModeAddFB2 fallback

- CMakeLists.txt
- cmake/VersioningUtils.cmake
Import the `VersioningUtils.cmake` script and use it to configure a libtool-style soversion for the `cogcore` library.
> CMake: Calculate and set a libtool soversion

- CMakeLists.txt
- cmake/DistTargets.cmake
This automatically adds `dist` and `distcheck` targets to the project.
> CMake: Import and use DistTargets.cmake

- core/cog-shell.c
Building with GLib 2.62 produces a bunch of the following warnings:
```
../core/cog-shell.c: In function ‘cog_shell_startup_base’:
../core/cog-shell.c:114:13: warning: G_ADD_PRIVATE
114 |     CogShellPrivate *priv = PRIV (shell);
|                           ^~~~~~~~~~~~~~~
```
This uses `cog_shell_get_instance_private()`, which is defined automatically by the `G_DEFINE_TYPE_*` macros and is the preferred way of obtaining a pointer to the instance private area anyway. GLib 2.4 or newer is needed, which was released in 2004, so this is not expected to introduce any issue.
> shell: Avoid G_ADD_PRIVATE warning

- platform/cog-platform-drm.c
Assign a better value to the variable that should be preventing constant
crtc updates but was failing to do so.
> drm: crtc continuously being reset

- CMakeLists.txt
- platform/cog-platform-drm.c
For each exported wl_resource, we now cache the imported gbm_bo object and the
corresponding framebuffer object, avoiding constant cycling of these resources.
Upon first export, we spawn all the relevant resources. On further exports, we
iterate over the buffer list to find the cached object, and reuse such an object
if it exists.
Each cached buffer is associated to the wl_resource lifetime through the
destroy listener that's set up on the resource object. The cached buffers are
cleaned up during teardown.
> drm: cache imported gbm_bo objects and corresponding DRM framebuffers

- .travis.yml
> Fix the toolchain SDK URL used in the CI 

- modules/cog-fdo-shell.c
- platform/pwl.c
- platform/pwl.h
PwlEGLData is removed in favour of PwlDisplay which now contains the data structures contained previously by PwlEGLData.
Also, the destroy_window () and pwl_display_egl_deinit () receives now a PwlDisplay as argument.
> pwl: PwlEGLData data is moved to PwlDisplay

- CMakeLists.txt
- data/cog.1
- data/cogctl.1
Import manual pages `cog(1)` and `cogctl(1)` from the Debian Cog  packaging repository at
https://salsa.debian.org/berto/cog/tree/6ebc0d4288463799a3480a78d45d9331fda63b60/debian
plus the needed CMake bits to install them, controlled by the `INSTALL_MAN_PAGES` configuration option (enabled by default) if the `COG_BUILD_PROGRAMS` is also enabled.
Thanks to Alberto Garcia for writing the manual pages and pointing them to us for inclusion in the repository.
> Add manual pages for cog and cogctl

- platform/cog-platform-fdo.c
Fixes:
```c
Thread 1 "cog" received signal SIGSEGV, Segmentation fault.
xkb_state_update_mask (state=0x0, base_mods=0, latched_mods=0, locked_mods=0, base_group=base_group@entry=0, latched_group=latched_group@entry=0, locked_group=0) at ../src/state.c:814
814	    prev_components = state->components;
```
> fdo: ensure xkb_data.state is not null before calling xkb_state_update_mask

- core/cog-platform.c
- platform/cog-platform-drm.c
- platform/cog-platform-fdo.c
To avoid cog_platform_try_load() loading equally-named symbols from
libcogcore.so when they are not defined in the specified platform
plugin, the plugin entrypoints are renamed to cog_platform_plugin_*.
> Adjust plugin entrypoint names

- CMakeLists.txt
- platform/cog-platform-fdo.c
By relying on the direct-display and content-protection Weston Wayland
protocols, the browser is now able to render video frames by passing them
directly to the display controller, without any additional GPU import in the
compositor. DMABufs are wrapped in sub-surfaces and positioned according to the
coordinates provided by WebKit.
Minimal support for multiple videos rendering support was added, although in
most cases the underlying hardware platform will be able to render only one
video at a time.
> Support for direct-display video content rendering

- platform/cog-platform-fdo.c
There's a bunch of EGL state (context, config etc.) that we don't use
or need, so we can just pull it out of the code.
> Remove redundant EGL state

- CMakeLists.txt
- cmake/FindWaylandProtocols.cmake
Improve `FindWaylandProtocols.cmake` to allow passing full paths (among other goodies) to `add_wayland_protocol()`, then use that to simplify the top-level `CMakeLists.txt`, along with imported targets and commands which modify the target instead of carrying around list variables.
----
Fixes #178
> CMake: Simplify FDO platform plug-in build definitions

- platform/cog-platform-fdo.c
Fixes:
```c
Program terminated with signal SIGSEGV, Segmentation fault.
#0  xkb_state_key_get_layout (state=state@entry=0x0, kc=kc@entry=50) at ../src/state.c:217
```
Backtrace:
```c
#0  xkb_state_key_get_layout (state=state@entry=0x0, kc=kc@entry=50) at ../src/state.c:217
#1  0x0000007f94c3ba6c in xkb_state_key_get_syms (state=state@entry=0x0, kc=kc@entry=50, syms_out=syms_out@entry=0x7fc6e1eba8) at ../src/state.c:864
#2  0x0000007f94c3c23c in xkb_state_key_get_one_sym (state=0x0, kc=kc@entry=50) at ../src/state.c:937
#3  0x0000007f90b6fd14 in handle_key_event (key=key@entry=50, state=state@entry=1, time=time@entry=1742858) at /home/buildroot/buildroot/rpi3/output/build/cog-0.4.0/platform/cog-platform-fdo.c:774
#4  0x0000007f90b6fe24 in keyboard_on_key (data=<optimized out>, …
```
> fdo: ensure xkb_data.state is not null before calling xkb_state_key_get_one_sym

- platform/cog-platform-fdo.c
Fixes:
```c
Program terminated with signal SIGSEGV, Segmentation fault.
#0  XkbKey (kc=kc@entry=45, keymap=0x0) at ../src/keymap.h:430
```
Backtrace:
```c
#0  XkbKey (kc=kc@entry=45, keymap=0x0) at ../src/keymap.h:430
#1  xkb_keymap_key_repeats (keymap=0x0, kc=kc@entry=45) at ../src/keymap.c:515
#2  0x0000007f92cc7ea4 in keyboard_on_key (data=<optimized out>, wl_keyboard=<optimized out>, serial=<optimized out>, time=191022, key=45, state=1)
at /home/buildroot/buildroot/rpi3/output/build/cog-0.4.0/platform/cog-platform-fdo.c:840
```
> fdo: ensure xkb_data.keymap is not null before calling xkb_keymap_key_repeats

- CMakeLists.txt
- platform/cog-platform-fdo.c
Load the default cursor theme and assign a surface with the left arrow image as cursor for the seat's pointer. This is a basic implementation which uses always the same cursor, even in HiDPI mode, so in that case the cursor will be tiny.
> fdo: Load and set a default pointer cursor

- cog.c
- core/cog-shell.c
- core/cog-shell.h
Store a reference of the GKeyFile configuration file specified on
the command line on the CogShell object, also providing a
cog_shell_get_config_file() accessor.
This makes the configuration file accessible from the platform
module, allowing access to any module-specific configuration.
> Keep a reference to the config GKeyFile on CogShell

- core/cog-launcher.c
This fixes error like
/mnt/b/yoe/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/cog/0.5.1-r0/cog-0.5.1/core/cog-launcher.c:529:9: error: cannot jump from this goto statement to its label
goto bad_format;
^
/mnt/b/yoe/build/tmp/work/cortexa7t2hf-neon-vfpv4-yoe-linux-gnueabi/cog/0.5.1-r0/cog-0.5.1/core/cog-launcher.c:531:27: note: jump bypasses initialization of variable with __attribute__((cleanup))
g_autoptr(SoupCookie) cookie = soup_cookie_parse (contents, NULL);
^
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> cog-launcher: Move auto ptr declation before goto statement

- cmake/FindWaylandProtocols.cmake
The optimization to check if WAYLAND_PROTOCOLS was set on the cmake
comamnd line was skipping the function implementations, making cmake
fail if it was used. The simple fix is to define the functions, then
bail of out WAYLAND_PROTOCOLS is already defined.
Signed-off-by: Joshua Watt <Joshua.Watt@garmin.com>
> cmake: Fix passing -DWAYLAND_PROTOCOLS= on command line

- cog.c
Load the URI passed as target to `window.open()` instead of leaving the signal unhandled, which results in no navigation at all. For now the same `WebKitWebView` is used because multiple views are not supported yet, but at least this makes certain websites usable.
> cog: Load target URI instead of ignoring window.open()

- platform/cog-platform-drm.c
Adding an env variable to specify preferred video mode for DRM platform.
Usage: 
```
export COG_PLATFORM_DRM_VIDEO_MODE=1920x1080
cog --platform drm http://google.com
```
> feat: user defined video mode selection

- platform/pwl.c
- platform/pwl.h
All the resources related to an individual wl_seat are encapsulated into a PwlSeat struct. A PwlDisplay contains a list of PwlSeat each one managing listeners and resources separately.
Signed-off-by: Pablo Saavedra <psaavedra@igalia.com>
> pwl: Support multiple wl_seats

- platform/pwl.c
Use plain `return` without a value in `display_add_seat()`, because the function signature does not include a return type.
> pwl: Do not return values from display_add_seat()

- cog.c
By default this option is disabled and an error page will be displayed when the page load fails due to a TLS error. However, by enabling this option the page load can resume and thus the TLS error is ignored. Use this option carefully and consider the security implications.
Based on #138, initially written by Philippe Normand (thanks @philn!)
> cog: Add a runtime option to ignore TLS certificate errors

- core/cog-shell.c
During collection of the GValues used to initialize the
View object, the reference count of GObject properties
will be increased. Therefore it's necessary to unset the
GValues once done with them to avoid leaking a reference.
For simplicity, let G_VALUE_COLLECT_INIT copy all the values
and just unset them all at once when done. This fixes any
potential leak with GObject-properties.
> core: unset properties after creating the view object

- core/cog-modules.c
- core/cog-shell.c
- core/cog-shell.h
1. Fail if the preferred module is not available.
2. Change a critical to warning as module unavailability is not a programming error.
3. Fill the GError in case of shell creation failure, also add a GError domain for this.
4.A few compilation warnings fixed.
> CogShell: several fixes during initialization

- core/cog-directory-files-handler.c
- core/cog-directory-files-handler.h
Support using the URI host as the first path component, when the `CogDirectoryFilesHandler.use-host` property is set. The default value of the property is `FALSE` to make the new behaviour opt-in and avoid breaking existing code.
There is also a commit to turn the base path into a construct-only property (which is good practice for `GObject` construction parameters), and another one to remove an unused definition.
Closes #225
> dir-handler: Allow usage of URI host as path component

- platform/cog-platform-drm.c
Limit max video mode width/height so the selection of best video mode is limited by these boundaries. It's useful, for example, on Raspberry Pi 4 that supports 4K. If I connect it to 4K screen, it will by default automatically select 4K mode but in some cases that's not what I want. When there's a lot of elements on the screen, CSS animations, etc., performance seems to suffer in 4K so I'd prefer to just force it to be max Full HD.
> drm: optionally limit max video mode width/height

- platform/cog-platform-drm.c
Fix destruction sequencing to avoid crashes during teardown of GBM and DRM resources. Buffers are now destroyed before anything else.
> DRM teardown crashes

- CMakeLists.txt
- platform/x11/CMakeLists.txt
- platform/x11/cog-platform-x11.c
The module is very basic in its nature, resampling the exported buffers
into a separate GL scene and using a dumb repaint loop to present that
scene in an X11 window. libxcb is used as the library through which
the X11 protocol is handled.
Very basic input (mouse, keyboard) is supported. The X11 window is
closable, but not (yet) through any keyboard shortcut.
This is intended as a minimal X11-functionality baseline, with
additional attention provided as required.
> Add initial X11-oriented platform module

- CMakeLists.txt
- cmake/FindWaylandProtocols.cmake
- cmake/FindWaylandScanner.cmake
- cog.c
- platform/cog-platform-drm.c
- platform/cog-platform-fdo.c
This includes the following improvements:
- CMake: Use an imported target for each dependency
- CMake: Include GNUInstallDirs after call to project()
- CMake: Match WaylandScanner find module output variable name
- CMake: Match WaylandProtocols find module output variable name
This supersedes #243 as well.
> Assorted CMake improvements

- platform/cog-platform-drm.c
- platform/cog-platform-fdo.c
- platform/common/egl-proc-address.h
- platform/x11/cog-platform-x11.c
Provide a common EGL proc address loader function that incorporates
a dlsym-based fallback in case eglGetProcAddress() refuses to find
an otherwise-existing entrypoint.
This should avoid some drivers that fail to handle proc address
requests for specific entrypoints, but have those entrypoints
exported as regular symbols loadable through dlsym().
> platform: add a common EGL proc address loader with dlsym fallback

- core/cog-shell.c
User code might still be using a view asynchronously when this
is removed from the shell. Since it's not 100% certain that
having a reference to the object after it's removed from the
view means that it's leaked, make it a debugging message instead
of a critical warning instead.
> cog-shell: make critical ref counting warning debugging message

- CMakeLists.txt
Fail the build if the Weston direct display support was enabled but the
WPEBackend-FDO Video Plane DMABuf extension was not found. The Weston
direct-display support cannot work without it.
> cmake: Make dmabuf extension mandatory for Weston direct-display support

- .travis.yml
Because it's a good idea to make sure PRs don't break it :smile:
> CI: Enable building the KMS/DRM platform module

- core/cog-webkit-utils.c
Make `cog_web_view_connect_default_error_handlers()` connect the default signal handlers only for those signals which do not yet have any handler connected. This avoids e.g. having a handler for `web-process-terminated` installed by `cog_web_view_connect_web_process_terminated_restart_handler()`
and then the default handler overriding its behaviour with a second handler connected after it by `cog_web_view_connect_default_error_handlers()`.
Fixes #230
> utils: Only connect default handlers when none already present

- core/cog-directory-files-handler.c
When checking whether a resolved path is a descendant of the base path in `cog_directory_files_handler_run()`, allow the resolved path to be the same as the base path. This is needed to allow URIs which point to the root of the base path (either without a path, or a single slash as path) and attempt to find an `index.html` file there.
This fixes a regression introduced by #265
> core: Allow resolving base path in URI files handler

- CMakeLists.txt
- core/cog-directory-files-handler.c
- core/cog-directory-files-handler.h
- core/cog-prefix-routes-handler.c
- core/cog-prefix-routes-handler.h
- core/cog.h
Add a new `CogPrefixRoutesHandler` class (which implements `CogRequestHandler`) and can dispatch a number of URI path prefixes to different handlers, with an optional fallback handler for unmatched URI paths.
Additionally, complement it with the addition of the `CogDirectoryFilesHandler:strip-components` property, which allows for removing URI path prefixes, which comes in handy after they have been matched by `CogPrefixRoutesHandler`.
> core: Add new custom URI scheme handler that routes based on path prefixes 

- platform/fdo/cog-platform-fdo.c
Sadly the CI didn't run in #269 :disappointed:  but it will now after #271 was merged :raised_hands:
> fdo: Fix include after #269

- platform/drm/CMakeLists.txt
- platform/fdo/CMakeLists.txt
Place built modules in `${CMAKE_BINARY_DIR}`, which allows to use them uninstalled more easily due to CMake setting the `DT_RUNPATH` of binaries to the top level build directory.
> cmake: Make it easier to use uninstalled platform modules

- CMakeLists.txt
- platform/headless/CMakeLists.txt
- platform/headless/cog-platform-headless.c
This new plugin relies on WPEBackend-FDO's SHM facilities. Buffers are not rendered, frame complete
notification clocks at 30 FPS.
> platform: Add basic headless platform plugin

- platform/drm/cog-platform-drm.c
Handle the wpe_fdo_shm_exported_buffer exports that might arrive on
the wpe_view_backend_exportable_fdo_client interface.
When that occurs, we craft a gbm_bo with the necessary flags that
would allow us to map the bo's underlying memory and write into it.
We still create a framebuffer object off of it, pretty much like we
do it for other types of bos.
The new buffer objects use the existing caching facilities. Each
buffer object, cached or newly created, is updated by mapping the bo
memory into the address space and copying over the data contained
in the shm area.
For now, only ARGB8888 and XRGB8888 SHM formats are handled. In both
cases the corresponding gbm bo will use the XRGB8888 format.
> drm: support wpe_fdo_shm_exported_buffer exports

- platform/fdo/cog-platform-fdo.c
When software-only GL rasterization is enforced (or when falling back
to it for whatever reason), the Wayland EGL platform implementation
can retreat to producing SHM-based buffers. When using the existing
wpe_view_backend_exportable_fdo_egl_client interface, these arrive as
wpe_fdo_shm_exported_buffer objects. This changeset introduces proper
handling for these types of exports.
This functionality is fairly new in WPEBackend-fdo, so the relevant
code is (where necessary) guarded with the HAVE_SHM_EXPORTED_BUFFER
macro that's enabled for the post-1.8.0 release series.
Once exported, we operate on the wl_resource and wl_shm_buffer objects
that relevantly describe this buffer. For any such export, we provide
a separate shared-memory region that is basis for its own wl_shm_pool
and the …
> fdo: support wpe_fdo_shm_exported_buffer exports

- CMakeLists.txt
The thing should be mature enough by now to be enabled by default.
Exception to this are different modifier issues that have to be
solved with different approaches around dmabuf management.
> drm: enable the platform module by default

- core/cog-config.h.in
- platform/fdo/CMakeLists.txt
- platform/fdo/cog-platform-fdo.c
Use the `WAYLAND_VERSION_{MAJOR,MINOR}` macros to check whether the FDO platform plug-in is being built against Wayland 1.10 or newer. This makes it unnecessary to check the version with CMake.
This also fixes a recent regression which caused `WAYLAND_1_10_OR_GREATER` to not be defined by CMake anymore.
> fdo: Use WAYLAND_VERSION_* instead of CMake check

- .github/workflows/ci-cross.yml
- .github/workflows/ci-native.yml
- CMakeLists.txt
- cmake/FindGObjectIntrospection.cmake
- docs/CMakeLists.txt
- docs/cog.toml.in
Add support for building documentation for the `cogcore` library using [gi-docgen](https://gitlab.gnome.org/ebassi/gi-docgen), and the corresponding CI steps to build and archive the documentation as an artifact. In the future we could also setup automatic deployment of the generated content to `wpewebkit.org` or to GitHub pages when a push to the main branch happens and/or a tag is created.
A preview (not kept updated) can be found at https://fugu.perezdecastro.org/Cog-0.0/
For now there is not a lot documented, but at least we need to start somewhere 😄
> Support building documentation using gi-docgen

- .github/workflows/ci-native.yml
Publishes the archived documentation artifacts after pushes to the main branch. Could be extended at some point for tags.
> CI: Publish docs on pushes to main branch

- CMakeLists.txt
- cog.c
- core/cog-platform.c
- core/cog-webkit-utils.h
- platform/drm/CMakeLists.txt
- platform/drm/cog-platform-drm.c
- platform/fdo/CMakeLists.txt
- platform/fdo/cog-platform-fdo.c
- platform/gtk4/CMakeLists.txt
- platform/x11/CMakeLists.txt
- platform/x11/cog-platform-x11.c
Update the minimum required versions to the following, which are all more than one year old:
- WPE WebKit 2.27.3, the oldest development version of the 2.28 series   which already has most of the features used by Cog.
- libwpe and WPEBackend-fdo 1.5.0, with the same reasoning.
This allows removing a bunch of conditional code.
Fixes #241
> Depend on WPE WebKit 2.28, libwpe+WPEBackend-fdo 1.5

- .clang-format
- .github/workflows/codestyle.yml
- data/check-style
Introduce tooling to check the coding style,and a CI worflow which runs it only on the changes introduced by a PR. The goal of checking only the changed code is to avoid having to run a full reformatting of the tree: instead, changes that modified existing code will slowly make the tree drift towards the desired status without introducing noise in the repository history.
There are is some trickery involved in getting this to work reliably:
- The `clang-format-diff` helper script is installed at different locations depending on the distribution. The `check-style` script checks a few locations that cover popular GNU/Linux distributions (Ubuntu, Debian, Arch Linux, Fedora); it can be improved as we see fit in the future.
- The `actions/checkout` step defaults to shallow clones of the single …
> CI: Add a CI job that runs clang-format on PR changes

- CMakeLists.txt
The D-Bus system bus policy config should reside in `CMAKE_INSTALL_DATADIR` rather than in `CMAKE_INSTALL_SYSCONFDIR`.
See:
https://gitlab.freedesktop.org/dbus/dbus/-/blob/ef55a3db0d8f17848f8a579092fb05900cc076f5/bus/CMakeLists.txt#L117
> CMake: install D-Bus policy configuration to CMAKE_INSTALL_DATADIR

- .github/workflows/codestyle.yml
- data/check-style
This is needed to make the code style checker work as intended (see #300 for an example failure).
> CI: Always use clang-format version 11

- .clang-format
- platform/drm/cog-platform-drm.c
Add the missing bits to support absolute pointer motion events.
Fixes #310
----
Note that this is completely untested, as I do not have around any input device that would generate absolute motion events.
@Mandrake-Lee: Could you apply this patch locally and test if it works for you? That would be helpful 🛠️
> drm: Handle POINTER_MOTION_ABSOLUTE input events

- platform/drm/CMakeLists.txt
Fix a typo in the call to `set_target_properties()`, which makes `libcogplatform-drm.so` be built into the expected location, and also correctly sets it to be compiled as C99.
> drm: Correctly set CMake target options

- .github/workflows/codestyle.yml
- data/check-style
Make CI code style checks use as input the same diff that would have been generated locally when running `data/check-style` to avoid situations in which running the script on a developer's machine would report no mistakes but the CI would insist that there are still some code style issues.
> codestyle: Use Git's diff on CI with same options

- .github/workflows/codestyle.yml
- README.md
- data/check-style
Change the obsolete Travis-CI badge to the ones provided by the new GitHub Actions workflows.
> README: Update status badges

- .github/workflows/ci-native.yml
The generated output has been improved, and also an upstream fix makes the wrapper script unneeded.
> CI: Bump to gi-docgen 2021.6

- CMakeLists.txt
This CMake option allows build Cog with/without the headless platform. The headless platform has dependency with WPEBackend-FDO not desiderable when you are not interested on that backend for example for the case of
the DRM with the WPEBacked-RDK.
Related to: c638d133b5375ddd3c368123b39b8ab37889c921
Signed-off-by: Pablo Saavedra <psaavedra@igalia.com>
> platform: Add COG_PLATFORM_HEADLESS cmake option

- .github/workflows/codestyle.yml
- data/check-style
Arrange to fetch the Git history needed to make `git diff` work from a pull request checkout, so the data/check-style can be invoked directly instead of relying on an external diff tool. This makes the CI code style checks run the same command that a developer would use locally, thus avoiding the situation in which the CI would complain that there are code style issues that were not reported in a local run.
> CI: Fetch Git history to use data/check-style

- CMakeLists.txt
- core/cog-host-routes-handler.c
- core/cog-host-routes-handler.h
- core/cog.h
Handler for custom URI scheme requests that can route requests to different handlers depending on the *host* component of the requested URI.
Optionally, if a “fallback” handler has been specified, it will be used to serve requests which do not match any of the routed hosts.
The set of available host map entries can be configured using [method@Cog.HostMapHandler.add] and
[method@Cog.HostMapHandler.delete]. For each request, map entries  are checked and the one that matches the URI *host* component will handle the request.
This handler is typically used in tandem with [class@Cog.DirectoryFilesHandler], the latter being typically a
fallback, or as the handler for a routed host.
> core: Add cog-host-routes-handler

- cog.c
- data/cog.1
Add a new `-F`/`--content-filter` command line option to the `cog` launcher, which allows specifying the path to a JSON rule set which will be compiled and used as content filter.
> cog: Add support for loading a JSON content filter

- platform/fdo/cog-platform-fdo.c
Make the `cog_fdo_platform_is_supported()` check only whether it is possible to connect to a running compositor, without doing additional busy work.
Closes #331
> fdo: Simplify checking for a running Wayland compsitor

- platform/fdo/cog-platform-fdo.c
- Enter fullscreen via DOM requests or keyboard key
- Exit fullscreen via keyboard key
> Implement DOM fullscreen requests in fdo backend

- .clang-format
- platform/fdo/cog-platform-fdo.c
Add code to do a cursory check on the Wayland protocols handled by the Wayland compositor in the `check_supported()` function. This makes sure that the FDO platform will be chosen if at least one of the shell protocols supported by the code are handled by the compositor.
Note that it is not needed to check for protocols from the base Wayland specification which every compositor is expected to implement (`wl_compositor`, `wl_shm`, `wl_seat`, etc.) because these will always be available.
As a related note, it would be neat to check that the EGL will be usable with the Wayland compositor, but there is no 100% reliable way without going through actual EGL initialization, so no check is added for this at the moment.
> fdo: Reintroduce checks on Wayland protocols

- platform/fdo/cog-platform-fdo.c
- platform/gtk4/cog-platform-gtk4.c
- Move the version checks to the top of the source files, accounting for the `WPE_CHECK_VERSION()` macro not present in older versions of libwpe.
- Designated initializers do not need to specify `NULL`/`0`/`false`, as it is the default.
- Fix some indenting around the touched lines.
> fdo, gtk4: Small cleanups after #329 and #341

- cog.c
webkit_web_context_set_tls_errors_policy() was introduced in 2.32,
can't be used for older versions...
> cog: Fix build for WebKit versions inferior to 2.32

- core/cog-launcher.h
Change `cog-launcher.h` to not re-declare `CogRequestHandler`, and instead include the header needed to bring its definition into scope. While at it, keep the style-checker happy.
Closes #261
> core: Avoid re-declaring CogRequestHandler

- docs/webdriver.md
This makes the Python example work out of the box.
Fixes #305
@lauromoura Thanks for you work!
> docs: webdriver: add missing imports

- core/cog-modules.c
If the `fdo` platform module is explicitly requested, fall back to `wl`, which is its new name. This is needed to ensure backwards compatibility and might be removed at some point in the future,  therefore a warning is also printed to let users know about this.
----
This is a follow-up to #351
> core: Use wl platform module as fallback for fdo

- platform/wayland/cog-popup-menu-wl.c
cog-popup-menu-wl.c:49:3: warning: redefinition of typedef 'CogPopupMenu' is a C11 feature [-Wtypedef-redefinition]
> wayland: Fix compiler warning.

- platform/drm/cog-platform-drm.c
Arrange to call `drmFreeDevices()` inside `check_drm()` and `init_drm()` to avoid leaking the arrays of devices returned by `drmGetDevices2()`.
> drm: Avoid leaking array of devices during checks

- CMakeLists.txt
- docs/CMakeLists.txt
Pass the correct `pkg-config` module name to `gi-docgen` depending on the version of libsoup in use: WPE WebKit builds with libsoup2 have API version 1.0, and builds with libsoup3 have API version 1.1.
> docs: Fix building documentation with libsoup3

- cog.c
- core/cog-platform.c
- core/cog-platform.h
- platform/drm/cog-platform-drm.c
- platform/gtk4/cog-platform-gtk4.c
- platform/headless/cog-platform-headless.c
- platform/wayland/cog-platform-wl.c
- platform/x11/cog-platform-x11.c
Use `GObjectClass.finalize` instead of `CogPlatformClass.teardown`. Now that `CogPlatform` derives from `GObject`, it is possible to reuse its functionality instead of having an ad-hoc vfunc that gets called immediately before destroying an instance. As a bonus, not only the implementations follow a more idiomatic GObject approach, but also it is not possible anymore to forget a call to `cog_platform_teardown()` before destruction.
> core: Remove unneeded CogPlatformClass.teardown vfunc

- .clang-format
- .github/workflows/codestyle.yml
- data/check-style
Update the `check-style` script and the CI job to use `clang-format` 13, which is the first version that supports combining `PointerAlignment: Right` with `AlignConsecutiveDeclarations: true`. This was unimplemented until recently, see https://reviews.llvm.org/D103245
While at it, do not let clang-format choose a different way of doing pointer alignment by setting `DerivePointerAlignment: false`.
> CI: Switch to clang-format version 13

- .github/toolchain.sh
- .github/workflows/ci-cross.yml
This does two things:
- Switches the ARM cross-toolchain builds to use the system-provided `wayland-scanner` binary, as it seems that newer versions of the toolchains either do not include it, or it is an ARM binary and thus CMake cannot run it to determine its version. Eventually this should be solved in the toolchain.
- Make toolchain download retries more reliable by also inspecting the exit code from the `curl` program and acting accordingly.
Closes #374
> CI: Improve cross-toolchain reliability

- CMakeLists.txt
Derive the location where to install platform modules from the `CMAKE_INSTALL_LIBDIR` variable (instead of `CMAKE_INSTALL_PREFIX`), instead of assuming that the directory is always called `lib/`
inside the prefix. This provides a saner default for distributors which use other kinds of locations, like multilib/multiarch systems.
----
(Thanks to @bertogg for spotting the issue!)
> cmake: Set default module location from CMAKE_INSTALL_LIBDIR

- launcher/cog-launcher.c
- platform/common/cog-gl-utils.c
- platform/common/cog-gl-utils.h
- platform/drm/CMakeLists.txt
- platform/drm/cog-drm-gles-renderer.c
- platform/drm/cog-drm-modeset-renderer.c
- platform/drm/cog-drm-renderer.c
- platform/drm/cog-drm-renderer.h
- platform/drm/cog-platform-drm.c
This is an alternative take on #360 — as it turns out using DRM/KMS exclusively is a can of works:
- In many cases graphics hardware imposes stringent restrictions on how to use hardware-assisted rotation support for DRM/KMS planes. For example on Intel GPUs typically one needs framebuffers with the `I915_FORMAT_MOD_Y_TILED` or `I915_FORMAT_MOD_Yf_TILED` modifiers for 90º/270º rotations, and on OMAP hardware one needs to manually use `ioctl()` and set one of the `OMAP_BO_TILED_*` flags in BOs which will be used for rotated scanout. Ad-hoc support for each hardware would be needed in `cog-platform-drm.c`.
- In some cases using one more hardware block results in more power consumption than using OpenGL because the GPU would be active and running anyway, and if unused the additional hardware …
> drm: Implement an OpenGL ES renderer with rotation support

- launcher/CMakeLists.txt
Explicitly place the built `cog` and `cogctl` binaries in the top level build directory. The location was moved in #376 without giving a second thought about it but it broke the `run-minibrowser` script from the WebKit repository, see: https://bugs.webkit.org/show_bug.cgi?id=234132
On top of preveting breakage of third party tooling, setting the build directory this way is more convenient for running programs for testing during development.
> launcher: Place built binaries in top level directory

- platform/gtk4/cog-platform-gtk4.c
cog_gtk4_platform_setup() is called before the CogShell had a chance to set its device scale factor
property, so we need to watch for property update notifications.
> gtk4: Fix mouse events handling

- docs/platform-drm.md
Improve the documentation for the DRM platform plug-in by documenting the `renderer` and `rotation` options, as well as providing an example about how to set then programmatically.
----
This is a follow-up to #371
> drm: Document the renderer and rotation options

- CMakeLists.txt
Make the `COG_MODULEDIR` macro expand to an absolute path at runtime to ensure that modules can always be found correctly. Otherwise, it is possible to configure the build e.g. with `COG_MODULEDIR=lib/cog/modules` (basically what is done after a18626b42c58c57208a5c17bd25d09e5d2aa5a16) and the relative path would end up in the built programs, resulting in failure to find the modules (unless, by chance, they are executed while the current directory matches the configured installation prefix.)
> cmake: Turn COG_MODULEDIR into an absolute path

- platform/gtk4/cog-platform-gtk4.c
The shader does not need this version.
> gtk4: Remove the requirement of a shader language version.

- platform/common/cog-gl-utils.c
- platform/common/cog-gl-utils.h
- platform/drm/cog-drm-gles-renderer.c
- platform/drm/cog-drm-renderer.h
- platform/drm/cog-platform-drm.c
- platform/gtk4/CMakeLists.txt
- platform/gtk4/cog-platform-gtk4.c
- platform/x11/CMakeLists.txt
- platform/x11/cog-platform-x11.c
This patch set moves the code that paints textured quads out from the DRM platform into the shared GL utility code, and makes the DRM, X11, and GTK4 platform use it—instead of each of them having slightly different copies of the code.
1. First, code that will be shared is moved from `cog-drm-gles-renderer.c` and into `cog-gl-utils.c`, and the DRM plug-in modified accordingly. This adds a new `CogGLRenderer` struct, functions to (de)initialize it, and for painting, accompanied by a comment explaining how to use the shared code.
2. The X11 plug-in is changed to link `libepoxy` in preparation for the next step.
3. The X11 and GTK4 plug-ins get their copy of the code removed and changed to use `CogGLRenderer` instead.
> drm, x11, gtk4: Refactor GL textured quad painting code

- platform/wayland/cog-platform-wl.c
Define bounds to the versions of Wayland protocol interfaces requested from the compositor on calls to `wl_registry_bind()`. This prevents the compositor from using newer features for which there is no client side implementation in Cog.
While at it, improve checks on protocol bits that depend on the version of the protocols being used, mainly for `wl_seat` and `wl_pointer` (which is part of the former) to use the correct checks at runtime, and to feature-check at build time (instead of depending on version of the Wayland library headers present at build time).
Fixes #396
> wl: Improve handling of Wayland protocol interface versions

- CMakeLists.txt
- cmake/FindWpeFDO.cmake
- platform/drm/CMakeLists.txt
- platform/gtk4/CMakeLists.txt
- platform/headless/CMakeLists.txt
- platform/wayland/CMakeLists.txt
- platform/x11/CMakeLists.txt
If not, there might be linking poisoning at compilation time, if a
custom wpebackend-fdo is used (by the uninstalled method, for
example) different to the one system-wide.
> build: Homogenize linked wpebackend-fdo version

- platform/x11/CMakeLists.txt
Add the `x11-xcb` module as dependency as well. The corresponding library is needed for its `XGetXCBConnection` symbol, which will be reported as missing when the platform plug-in was built with the `--as-needed` linker flag.
> x11: Fix underlinking when --as-needed is used

- platform/wayland/cog-platform-wl.c
When binding to the compositor interface, try to pick version 3, which introduced the support for setting scaling (i.e. for HiDPI outputs). Add the needed guards and runtime checks to use the new features only where available.
> wl: Use wl_compositor v3 features if available

- platform/wayland/cog-platform-wl.c
Ensure that version selection for the `wl_seat` interface is inside the range *[3, 7]*; and properly guard usage of `wl_seat_listener::name`.
> wl: Fix request of wl_seat version and guard feature usage

- platform/wayland/cog-platform-wl.c
> Fix WPE_FDO_CHECK_VERSION macro name and fdo buffer release function name.

- CMakeLists.txt
- platform/wayland/CMakeLists.txt
- platform/wayland/cog-platform-wl.c
For some reason this option was enabling content protection as well, since that is a separate option that merely depends on direct display move it under COG_WESTON_CONTENT_PROTECTION.
We also need to fix pkg-config search to look for libweston protocols starting with weston version 8(first to introduce direct display), the current weston development branch uses version 11 so lets include that as well.
We also need to [fix the client protocol header names](https://github.com/Igalia/cog/blob/d2720103ff8a5c3c5c056487586ed0b5acdc2b91/cmake/FindWaylandProtocols.cmake#L142) as the current ones are invalid.
> Fix COG_WESTON_DIRECT_DISPLAY build

- launcher/cog-launcher.c
A valid scale factor needs to be set before shell startup as
otherwise it breaks the drm platform.
Fixes https://github.com/Igalia/cog/issues/401
> launcher: set device scale factor before cog_shell_startup

- data/check-style
The script is set to run strictly at the beginning. Returning 1
from the function results the script to exit quietly, which is
very unhelpful, as it means the moment somebody who does not have
clang-format-diff installed runs cmake, the git hook gets copied
and from that moment running simple "git commit" exits with no
message whatsoever, making one wonder why git broke.
It is not necessary to return 1, as the existence of the program
is checked based on the captured string. Therefore, removing the
return will result in the check working correctly and printing an
error when the tool is not installed, which is much better.
> data/check-style: fix broken git commit without installed tools

- .github/workflows/ci-cross.yml
- .github/workflows/ci-native.yml
- CMakeLists.txt
In order to nudge packagers into using libsoup3, make it slightly more convenient by being the default.
> cmake: Enable usage of libsoup3 by default

- platform/drm/cog-platform-drm.c
- platform/gtk4/cog-platform-gtk4.c
- platform/wayland/cog-platform-wl.c
The new API was introduced in the [libwpe 1.13.2 development release](https://wpewebkit.org/release/libwpe-1.13.2.html). Typically we support building Cog with one or two major release series back of the main dependencies (libwpe, wpebackend-fdo, wpewebkit), so
add guards to use the `wpe_view_backend_set_target_refresh_rate()` only on newer versions.
> drm, wl, x11: Use wpe_view_backend_set_target_refresh_rate() conditionally

- CMakeLists.txt
- launcher/cog-launcher.c
Pass `--proxy=http://ip:port` and optionally `--ignore-host=hostname` to configure
a list of hostnames that will not be proxied.
> launcher: Add command-line option to enable network proxy support

- core/cog-shell.c
- platform/common/egl-proc-address.h
- platform/drm/cog-drm-modeset-renderer.c
- platform/gtk4/cog-platform-gtk4.c
This includes a number of assorted small cleanups:
```
7e557b6 drm: Avoid warning about mismatched pointer types
4143d6d gtk4: Remove egl-proc-address.h inclusion
8b8c373 common: Mark load_egl_proc_address() as inline
37ef997 core: Fix property references in documentation comments
```
> Assorted small cleanups

- CMakeLists.txt
- launcher/cog-launcher.c
Recognize `--proxy`/`--ignore-host` only when the version of WebKit being used supports the proxy API. While at it, do the check with `WEBKIT_CHECK_VERSION()` directly in C code, instead of relying on adding more gunk to the CMake build system.
----
It was only after merging https://github.com/Igalia/cog/pull/462 that I noticed that the version check could be done in C, and that usually we prefer to not have CLI options for unsupported features.
WDYT @philn, is there some reason to keep recognizing the CLI flags even if unsupported? Alternatively, we could raise the minimum supported WebKit version to 2.32, and avoid the conditional compilation.
> launcher: Only include proxy options if supported

- core/meson.build
- docs/meson.build
- launcher/meson.build
- meson.build
- meson_options.txt
- platform/common/meson.build
- platform/drm/meson.build
- platform/gtk4/meson.build
- platform/headless/meson.build
- platform/meson.build
- platform/wayland/meson.build
- platform/x11/meson.build
I will leave the following for follow-up patches:
The reason is that I would like to have the Meson build system landed _first_ without removing the CMake one, to avoid having a gap of time between with failed WebKit builds after removing the CMake build system and before landing the needed changes on the WebKit repository to start using Meson.
> Add new Meson build system

- core/cog-directory-files-handler.h
- core/cog-platform.h
- core/cog-shell.c
- core/cog-utils.h
- platform/wayland/cog-popup-menu-wl.c
- platform/wayland/cog-popup-menu-wl.h
This includes two commits:
- One removing unneeded forward-declarations of `struct`s which get defined anyway by GLib/GObject/WebKit headers. 
- Removing an unused variable.
> Clean up the code of some warnings produced by Clang 14

- core/cog-gamepad-manette.c
- core/cog-gamepad-noop.c
- core/cog-gamepad.h
- core/cog.h
- core/meson.build
- meson.build
- platform/drm/cog-platform-drm.c
- platform/gtk4/cog-platform-gtk4.c
- platform/wayland/cog-platform-wl.c
- platform/x11/cog-platform-x11.c
The current implementation is based on libmanette. If libmanette is available a noop implementation is used.
Depends on https://github.com/WebPlatformForEmbedded/libwpe/pull/88
> Add gamepad implementation.

- core/cogcore.pc.in
Arrange for the generated `cogcore.pc` file to include the version of the `wpe-webkit-1.x` dependency, instead of hardcoding `1.0`; this solves issues when Cog was configured against `wpe-webkit-1.1` where the `.pc` file would have the wrong version.
The switch from `Requires.private` to plain `Requires` is needed to let `pkg-config` add the WPE WebKit library in the output for `pkg-config cogcore --libs`, otherwise users need to specify
both `cogcore` and `wpe-webkit-1.x` as dependencies, when using `cogcore` should be enough.
> cmake: Write correct wpe-webkit requirement in .pc file

- core/meson.build
Add the Cog core library dependencies as requirements to be listed in the generated `cogcore.pc` file. Otherwise users would need to manually specify e.g. the WPE WebKit library by hand for linking, while it is preferable to have `pkg-config` list it itself.
> core: Add missing dependencies in generated .pc file

- cmake/FindWpeFDO.cmake
... because target "PkgConfig::WpeFDO" is imported but not globally visible in cmake/FindWpeFDO.cmake.
Notice that this issue is not reproducible in CMake v3.22.
CMake doc [1][2] says:
```
The scope of the definition of an IMPORTED target is the directory
where it was defined. It may be accessed and used from
subdirectories, but not from parent directories or sibling directories.
The scope is similar to the scope of a cmake variable.
It is also possible to define a GLOBAL IMPORTED target which is
accessible globally in the buildsystem.
```
[1] 3.16: https://cmake.org/cmake/help/v3.16/manual/cmake-buildsystem.7.html#imported-targets
[2] latest: https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#imported-targets
**Note:** _Target branch is cog-0.14 since there is not longer …
> cmake: Fix CMake (v3.16) cannot create ALIAS target "Wpe::FDO" error

- core/cog-gamepad.c
Fixes:
```c
../core/cog-gamepad.c: In function ‘cog_gamepad_setup’: ../core/cog-gamepad.c:73:68: error: invalid use of undefined type ‘const struct wpe_gamepad_provider_interface’
73 |     s_provider_interface = (struct wpe_gamepad_provider_interface) * s_backend->provider;
|                                                                    ^
../core/cog-gamepad.c:73:26: error: ‘s_provider_interface’ has an incomplete type ‘struct wpe_gamepad_provider_interface’
73 |     s_provider_interface = (struct wpe_gamepad_provider_interface) * s_backend->provider;
|                          ^
../core/cog-gamepad.c:74:25: error: invalid use of undefined type ‘struct wpe_gamepad_provider_interface’
74 |     s_provider_interface.get_view_backend = gamepad_get_view;
|                         ^ …
```
> Fix build without gamepad manette

- meson.build
Allow using `wpe-webkit-1.1` in place of `wpe-webkit-2.0`, to ease building on systems which provide the former.
Commit be29794 changeg the dependency when using libsoup3 from `wpe-webkit-1.1` to `wpe-webkit-2.0`, but there are at the moment no tangible differences between both.
> meson: Allow fallback to wpe-webkit-1.1

- meson.build
Set up the compiler to build in C11 mode by default. This should be fine, the specification has been around for >10 years and any compiler capable of building WebKit and the rest of the dependencies supports C11 anyway.
Fixes #498
> meson: Build in C11 mode by default

- platform/wayland/meson.build
As the comment says, cog-platform-wl.c needs drm_fourcc.h to build properly when wayland_weston_direct_display is enabled.
However, libdrm.pc doesn't specify "include/libdrm" as part of its includedir but whether in its cflags. So use the compile_args dep instead of includes to fix the build failure.
Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
> wl: Fix libdrm dependency when protocols are used

- core/cog-utils.c
needed for int64_t
```
ninja: job failed: clang -Icore/libcogcore.so.9.2.0.p -Icore -I../core -I/usr/include/wpe-webkit-1.1 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/libsoup-3.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/wpe-1.0 -I/usr/include/libdrm -I/usr/include/libmanette -fcolor-diagnostics -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O2 -g -DCOG_INSIDE_COG__=1 -DCOG_USE_SOUP2=0 -O3 -flto=thin -march=native -fPIC -fstack-clash-protection -fstack-protector-strong -fcf-protection -pipe -fomit-frame-pointer -fno-plt -fdiagnostics-color=always -O3 -flto=thin -DNDEBUG -march=native -fPIC -fstack-clash-protection -fstack-protector-strong -fcf-protection -fomit-frame-pointer -fno-plt -fdiagnostics-color=always -fPIC -pthread …
```
> utils: add missing stdint.h include

- meson.build
This avoids a few dependency checks and makes it easier to build Cog when targeting a generic WPE backend.
> meson: Avoid subdir when no platform plugins configured

- platform/wayland/meson.build
Weston 11 was released recently and the weston development branch is now using libweston-12-protocols.
> Add support for weston 12 protocols

- NEWS
- core/cog-directory-files-handler.c
- core/cog-platform.c
- core/cog-utils.c
- docs/overview.md
- launcher/cog-launcher.c
- launcher/cogctl.c
- platform/wayland/os-compatibility.c
- platform/x11/cog-platform-x11.c
Motivated by various occurrences of "a"/"an" mix-ups in errors (it's "an" before a vowel _sound_, not before a written vowel in general), I ran [codespell](https://github.com/codespell-project/codespell) and fixed all typos it found. I was unsure whether to squash them all into a single commit, so I separated code, comments, docs and NEWS. I'm happy to change that if suggested.
> Fix typos in errors, warnings, help strings, comments and docs

- core/cog-webkit-utils.c
The API is deprecated and the functionality removed from WebKit.
> webkit-utils: don't use WebKit plugins API

- launcher/cog-launcher.c
- meson.build
- meson_options.txt
This will allow building cog after https://github.com/WebKit/WebKit/pull/5944/
> Drop support for wpe-webkit-1.1, build only for libsoup 3 by default, and don't try to enable sandbox when using new WebKit API

- docs/platform-drm.md
Add the missing documentation for the environment variables honored by the DRM/KMS platform plug-in.
> drm: Document supported environment variables

- platform/wayland/cog-platform-wl.c
The `hardware_key_code` param for `wpe_input_keyboard_event` is not utf32 but rather the raw keycode as it is not intended to change based on keymaps.
Raw hardware keycodes are translated by [keyCodeForHardwareKeyCode](https://github.com/WebKit/WebKit/blob/wpewebkit-2.39.5/Source/WebCore/platform/libwpe/PlatformKeyboardEventLibWPE.cpp#L446-L765).
> wl: fix hardware keycodes

- docs/platform-headless.md
- platform/headless/cog-platform-headless.c
Recognize the parameters string as the maximum frame rate (FPS/Hz) at which frames are acknowledged.
> headless: Allow configuring the maximum refresh rate

- .github/workflows/ci-cross.yml
- .github/workflows/ci-native.yml
- .github/workflows/codestyle.yml
Restrict `push` jobs to development branch and release branches, to avoid having a duplicate set of CI jobs when filing a PR associated to the push event to the branch from which the PR was created. Also, restrict `pull_request` jobs to those PRs targeting the same set of branches.
> CI: Avoid duplicated jobs on pull requests

- .github/toolchain.sh
Improve the logic around reusing a cached toolchain installation by storing the toolchain installer checksum file instead of the time of installation. This way we can check that the cached installation corresponds to what is expected, or do it afresh otherwise. This is more robust than the existing approach that trusts that any file on the server newer than the installation timestamp should be preferred.
> CI: Save checksum of toolchain installer insted of timestamp

- .github/workflows/ci-cross.yml
- .github/workflows/ci-native.yml
- core/cog-shell.c
- launcher/cog-launcher.c
- meson.build
- meson_options.txt
This brings the contents of the `mcatanzaro/next` branch, which already supported building against the 2.0 API, and re-adds support for the 1.1 API (which we want to keep supporting as long as it is part of WebKit).
Thanks to @mcatanzaro, @carlosgcampos, and @TingPing for making the 2.0 API support possible.
> Add support for the new WPE WebKit 2.0 API

- platform/wayland/cog-platform-wl.c
- platform/x11/cog-platform-x11.c
Adjust the amount of page scrolled when receiving scroll wheel events to make scrolling feel snappier in the Wayland and X11 platforms snappier. The 120 step value comes from the fact that libinput includes the `libinput_event_pointer_get_scroll_value_v120()` function, which in turn is based on a recommendation contained in a design document written by Microsoft.
Also, the table of deltas for X11 has its values reversed, to make the scroll feel more natural, i.e. "pulling" a scroll wheel makes the page scroll downwards. This matches defaults in common desktop environments.
> x11, wl: Make scroll wheel behaviour snappier

- platform/wayland/cog-platform-wl.c
wl_keyboard protocol sends key events as a physical key signals on the keyboard (limited to 256 - 8 bits).  The XKB protocol doesn't share this limitation and uses extended keycodes and it restricts these names to at most 4 (ASCII) characters:
```
xkb_keycode_t keycode_A = KEY_A + 8;
```
Ref: xkb_keycode_t section in https://xkbcommon.org/doc/current/xkbcommon_8h.html
> wl: Document why keyboard_on_key needs the most 4 (ASCII) characters

- data/cog.1
- launcher/cog-launcher.c
On some cases it is useful to be able to specify the Cog platform plugin and the platform parameters via environment variables.
For example: bots running CI tests may be executing the same command to start Cog but each bot can be configured to use a different platform plugin via enviroment variables.
Another example: The script `run-benchmark` from WebKit doesn't allow the user to pass custom command-line parameters to the browser, so with this environment variables the user should be able to select the platform parameters for Cog via the environment.
> Allow to pass the values for platform and platform-params via env vars.

- launcher/cog-launcher.c
* GOptionEntry documentation says the following:
> If arg type is G_OPTION_ARG_STRING or G_OPTION_ARG_FILENAME, the location will contain a newly allocated string if the option was given. That string needs to be freed by the callee using g_free(). Likewise if arg type is G_OPTION_ARG_STRING_ARRAY or G_OPTION_ARG_FILENAME_ARRAY, the data should be freed using g_strfreev().
This PR ensures to free all those types from the GOptionEntries that we currently use. Most of them were already freed but a few of them were missing.
It switches some of them to use [`g_clear_pointer()`](https://docs.gtk.org/glib/func.clear_pointer.html) as that helper function sets the pointer to `NULL` after freeing it. Is also safe to call it with a reference pointing to `NULL`.
There is one GOptionEntry missing on …
> Ensure to free the GOption values that will not longer be needed

- platform/drm/cog-platform-drm.c
When a key event occurs, Cog will ask WPE from its managed XKB context for an associated key code. If WPE fails to acquire a default XKB context, requests to fetch the state/key-code is undefined. This will cause Cog to fault on a first detected input.
Part of the issue is that `wpe_input_xkb_context_get_default` does not gracefully handle failed attempts to initialize the XKB context \[1\]. Assuming WPE does give Cog proper notice of a fail context, Cog should also limiting attempts to query state information from a context that is not available (assuming Cog desires to handle an inputless environment).
This commit tweaks the key event handling to drop any key event if the XKB context is not available.
\[1\]: https://github.com/WebPlatformForEmbedded/libwpe/pull/126
> drm: ignore key event if no xkb context is available

- core/cog-platform.c
- core/cog-platform.h
- launcher/cog-launcher.c
Take the logic of `platform_setup_once()` out from the launcher into the core library. This will allow reusing the same implementation in other programs.
> core: Move platform selection logic into the library

- core/cog-platform.h
- core/cog-shell.c
- core/cog-view.c
- core/cog-view.h
- core/cog.h
- core/meson.build
- launcher/cog-launcher.c
Add a new `CogView` class, which extends `WebKitWebView` to avoid needing to specify the view backend for each instantiated view. Instead, the creation is delegated to the current CogPlatform, in one of the following two ways:
- Overriding a new `get_view_type` vfunc, which returns the `GType` of a `CogView` subclass specific to the platform plug-in. The custom view class needs to implement a `create_backend` vfunc that creates the view backend to use.
- Letting the core library use its fallback `CogView` subclass, which relies on the platform's `get_view_backend` vfunc. This matches the existing behaviour.
This way platform plug-ins can opt-in to the new behaviour by implementing their own `CogView` subclass, and unchanged plug-ins will continue working during the transition.
> core: Introduce a new CogView class

- core/cog-fallback-platform.c
- core/cog-fallback-platform.h
- core/cog-modules.c
- core/meson.build
- docs/cog.toml.in
- docs/platform-fallback.md
- launcher/cog-launcher.c
This PR includes two commits:
- The first adds a new `CogFallbackPlatform` implementation, which can handle plain WPE backends (like WPEBackend-rdk). This gets built into the core library and thus is always available, instead of building it as a plug-in.
- The second removes the ad-hoc handling of plain WPE backends, which are left to be handled by `CogFallbackPlatform`.
> Add a CogFallbackPlatform implementation

- core/cog-view.c
- core/cog-view.h
- docs/platform-wl.md
- platform/drm/cog-platform-drm.c
- platform/gtk4/cog-platform-gtk4.c
- platform/wayland/cog-platform-wl.c
- platform/x11/cog-platform-x11.c
Pick the key binding handling from the Wayland platform plug-in, and move it into the core library. A new `cog_view_handle_key_event()` method takes care of detecting supported key bindings or actually sending the events to the view backend otherwise. In order to support cases where key bindings are not desirable (e.g. kiosks) it is possible to disable key binding support.
The only bit missing to move is the <kbd>F11</kbd> key binding to (un)fullscreen as the operation may need platform view specific actions, so for now the handling for this binding is left as it was in the Wayland platform plug-in. This can be improved later on in a follow-up patch.
> core: Move key binding handling into CogView

- data/cog.1
- launcher/cog-launcher.c
Add a new `--no-key-bindings` command line flag which can be used to disable the `CogView` built-in key bindings.
----
This is a follow-up to #574
> launcher: Add CLI flag to disable built-in key bindings

- platform/wayland/meson.build
Weston 12 was released recently and the weston development branch is now using libweston-13-protocols.
> Add support for weston 13 protocols

- launcher/cog-launcher.c
GApplication warns if you do not handle activate.
For now this does nothing, typically it would focus the main window of an application, which doesn't apply to many of Cog's platforms.
> launcher: Handle GApplication::activate

- platform/gtk4/cog-platform-gtk4.c
This is just a small quality of life improvement where entering "example.org" into the entry will prefix "https://".
> gtk4: Prefix a scheme if none provided

- platform/drm/cog-platform-drm.c
imx6 crashes when trying drm backend. This depends heavily on board used and this fix is generic. Doesn't affect existing configs but just fixed edge case for specific board when no default endoder+crtc was found
> drm: Fix crash on imx6 when no current encoder+crtc is bound

- core/cog-shell.c
WebKitWebView inherits from GObject so it is not needed to do g_object_ref_sink on it. It fixes the problem with deleting the view after receiving "close" signal.
> Fix deleting the view after signal close

- platform/wayland/cog-platform-wl.c
Configure an opaque region for the Wayland surface also when not fullscreened, as long as the web view background color is set to be opaque. This should slightly improve performance in compositors which take the opaque region hint into account also for non fullscreen surfaces.
> wl: Set opaque region if possible also when windowed

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.h
Move common definitions to cog-utils.h. The relevant structs are renamed as CogWl(Axis|Keyboard|Output|Pointer|Touch|Xkb)
Also the event_serial is moved inside of the CogWlKeyboard.
> wl: Create cog-utils-wl.h

- .check-style-ignore
- data/check-style
Add support for reading a `.check-style-ignore` file, with a regex in each line for ignored style checker paths.
Fixes #615
> check-style: Support reading a file with ignored paths

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-platform-wl.h
- platform/wayland/cog-utils-wl.h
These changes are motivated towards the progress of being able to have more than one view:
* Move declaration of CogWlPlatform to a header file
* More fix code-style in cog-platform-wl.c
* Encapsulate the seat resources inside of CogWlSeat. All the related resources to an individual wl_seat are encapsulated into a CogWlSeat struct. The CogWlDisplay contains a CogWlSeat (the first registered).
* Redefine wl_data and egl_data as CogWlDisplay. The CogWlDisplay is defined in cog-utils-wl.h. Also wl_data and egl_data definition are renamed as s_display.
> Several code cleanups and refactorings

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.h
Add missing include and fix access to the window through the view's associated `CogPlatform`.
----
The build with libportal got broken in #619
> wl: Fix build with libportal enabled after e533fce

- core/cog-platform.c
Emit a warning when trying to call `cog_platform_init_web_view()` in case the platform in use defines both `.get_view_type` and `.init_web_view`, because the latter shall not be defined when `.get_view_type` is in use.
> core: Warn on both get_view_type and init_web_view defined

- .github/workflows/ci-native.yml
Change the base images for the native CI builds to Ubuntu 22.04 LTS. In turn, this allows to use system packages for gi-docgen, meson, and libportal, thus removing the need for manually-installed Python packages. The later makes the build faster to complete.
> CI: Switch native builds to Ubuntu 22.04 LTS

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.h
- platform/wayland/cog-view-wl.c
- platform/wayland/cog-view-wl.h
In the **Platform** side the fullscreen enter/exit logic was cleaned up, simplified and encapsulated in the `cog_wl_platform_[enter|exit]_fullscreen` functions.
The `CogWlPlatform` is not responsible of having in consideration the state of the View. It is limited to do store the previous geometry, to set the new window geometry and to make the adjustments in the corresponding shell. Finally, the **View** associated to the **Platform** is notified using the new `cog_wl_view_[enter|exit]_fullscreen` functions and relies on the View to do the rest. The CogWlView reacts those notifications by sending the `wpe_view_backend_dispatch_did_enter_fullscreen` and `wpe_view_backend_dispatch_did_exit_fullscreen` according with the notification.
> wl: Decouple the fullscreen logic in CogWlPlatform and CogWlView

- core/cog-platform.c
- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-platform-wl.h
- platform/wayland/cog-view-wl.c
All the initialization done in the init_web_view() is now relocated  inside of the cog_wl_view_init(). To make this possible all the code     related to the "run-file-chooser" and "mouse-target-changed" signals     have be moved from the cog-platform-wl to the cog-view-wl.
This change makes the Wayland platform compatible with the check  implemented in the cog_platform_init_web_view(): "CogWlPlatform class    defines both .get_view_type and .init_web_view the latter should be   removed."
Also adds again the early return in cog_platform_init_web_view() if class defines both .get_view_type and .init_web_view.
> wl: Remove CogWlPlatform::init_web_view()

- core/cog-directory-files-handler.h
- core/cog-export.h
- core/cog-gamepad.h
- core/cog-host-routes-handler.h
- core/cog-modules.h
- core/cog-platform.h
- core/cog-prefix-routes-handler.h
- core/cog-request-handler.h
- core/cog-shell.h
- core/cog-utils.h
- core/cog-view.h
- core/cog-webkit-utils.h
- core/meson.build
Change the build options to use “hidden” visibility by default, and mark only the symbols that are part of the public API with the COG_API macro. This prevents library private symbols from leaking to the global symbol namespace even if they are not declared as “static”, and also makes the ELF PLT smaller which prevents accidental symbol overriding and improves load times.
> core: Declare public symbol visibilities

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-view-wl.c
- platform/wayland/cog-view-wl.h
The cog_wl_platform_resize_window() is moved to the View class as cog_wl_view_resize().
All the cog_wl_view_resize() are triggered inside of cog_wl_platform_configure_geometry() since the resize is a reaction to a change in the geometry of the Window.
> wl: Move cog_wl_platform_resize_window() to View as cog_wl_view_resize()

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-view-wl.c
The patch fixes a basic logic bug inside of the `on_export_wl_egl_image()`. The error is in the incorrect use of scale_factor (actually defined for the WebPage zooming) instead of the `current_output->scale` for validating the exported image geometry.
The change also unifies inside of the new `validate_exported_geometry()` function the shared code used for validating the sizes of the exported images.
**This fixes regression added in e533fce.**
**Thanks** to Adrian Perez de Castro <aperez@igalia.com> for reporting the issue.
> wl: Fix the validation of the exported image in outputs with scale factor

- platform/wayland/cog-platform-wl.c
This PR includes two commits which improve robustness when handling setting Wayland surface sizes:
- First, only read the `COG_PLATFORM_WL_VIEW_{WIDTH,HEIGHT}` environment variables only once during instantiation of the `CogWlPlatform` instance. There is no need to read those every time the surface is resized. This also brings in a helper function to do more thorough validation of the values from the environment variables.
- Second, use `g_return_if_fail()` to check that the width and height passed to `cog_wl_platform_configure_geometry()` are non-zero.
> wl: Make setting surface sizes more robust

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-platform-wl.h
- platform/wayland/cog-utils-wl.c
- platform/wayland/cog-utils-wl.h
- platform/wayland/cog-view-wl.c
There is not longer a static global popup_data definition inside of the platform. Instead of this the Platform will have attached a CogWlPopup instance.
It is the handling of the CogWlPopup responsibility of the CogWlPlatform object. For example, the cog_wl_platform_popup_create() and the cog_wl_platform_popup_destroy() will deal with the set and unset of the reference to the popup object inside the CogWlPlatform.
Because this reason, the CogWlView just relies on the CogWlPlatform for the creation and the rest of the life-cycle of a CogWlPopup now. All this is simply triggered by the on_show_option_menu() handler.
There are also other trivial refactorings:
* The cog_wl_compositor_create_surface() is moved to the cog-utils-wl for convenience.
* The popup auxiliary structs and callback …
> wl: Refactor popup_data as CogWlPopup

- platform/wayland/cog-utils-wl.c
... inducted by the the **xdg_popup::popup_done** handler.
This change fixes the `xdg_popup_on_popup_done()` in `platform/wayland/cog-utils-wl.c`. Now, the function resets the the `Platform::popup` if the destroyed popup is the same than the one
referenced in the **Platform**.
> wl: Fix possible invalid access to Platform:popup

- core/cog-shell.c
- core/cog-shell.h
- core/cog-viewport.c
- core/cog-viewport.h
- core/cog.h
- core/meson.build
- examples/meson.build
- examples/viewport.c
- meson.build
- meson_options.txt
- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-platform-wl.h
- platform/wayland/cog-view-wl.c
- platform/wayland/cog-view-wl.h
This PR brings in the following:
- A new `CogViewport` class, which represents an “output” to display one of a set of view.
- Adapting `CogShell` to use a viewport instead of a single view. At some point we will want to uncouple the shell (see #634) but this replacement is enough for now.
- Add an `examples/viewport.c` example program which shows how to switch between among the views of a viewport.
- Adapt the Wayland platform plug-in to no longer assume that there is a single view. 
I would recommend reviewing each commit separately.
> Introduce CogViewport, add support in the Wayland plug-in and example program

- platform/meson.build
> wl: Fix Meson configure error when Cog is build only for wayland

- core/cog-platform.c
Add GLIB_CHECK_VERSION to verify if we really can use the g_warning_once and avoid the undefined reference to g_warning_once link error.
> Fix build with using glib<2.63.1

- core/cog-modules.c
- examples/viewport.c
- launcher/cog.c
This brings in two related commits which make it a bit simpler to use the module loading API. Namely:
- Allow passing the same directory more than once to `cog_modules_add_directory()`, or directories with plugins which have the same name. Duplicates will be skipped, and that prevents potential issues with multiple installations of the same module, and avoids programs needing to track which directories have been already scanned to avoid passing the same path more than once.
- Remove the need to do an initial call to `cog_modules_add_directory(COG_MODULEDIR)` to scan the default module path. This is now done implicitly.
> core: Add some convenience to the module loader

- platform/drm/cog-platform-drm.c
I have a touchscreen:
```
cog -P drm -O renderer=gles,rotation=1
```
but the touchscreen libinput  report `Rotation` is not available 
```
$ libinput list-devices
Device:           Goodix Capacitive TouchScreen
Kernel:           /dev/input/event2
Group:            2
Seat:             seat0, default
Capabilities:     keyboard touch 
Tap-to-click:     n/a
Tap-and-drag:     n/a
Tap drag lock:    n/a
Left-handed:      n/a
Nat.scrolling:    n/a
Middle emulation: n/a
Calibration:      identity matrix
Scroll methods:   none
Click methods:    none
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   n/a
Rotation:         n/a
```
so I rotate touchscreen use device tree,then touch limit raw region when  rotate screen,this patch fix it when rotate angle  on 90 or 270.
By the way,I …
> Fix touch limit raw region when  rotate screen

- core/cog-platform.c
- core/cog-platform.h
- core/cog-view.c
- docs/cog.toml.in
- docs/running.md
- examples/viewport.c
- launcher/cog-launcher.c
- launcher/cog.c
- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.c
- platform/wayland/cog-view-wl.c
Remove the `cog_platform_configure()` utility function, because at this point it does not do much else than calling `cog_platform_new()` and `cog_platform_setup()`. Instead, make sure that the platform instance is a global singleton and that it is created on-demand on the first call of a the `cog_platform_get()` accessor.
In order to allow manually indicating which platform plug-in to use, a new `cog_init()` function is added. While at it, make it unnecessary for programs to always call `cog_modules_add_directory()` if they only need to use the default module path.
The upside of these changes is that the API gets much more convenient to use, and in the simplest of cases, it is enough to let the library initialize the platform instance. The one-time configuration using …
> core: Remove cog_platform_configure() function

- core/cog-modules.c
- core/cog-platform.c
Move handling of the `COG_MODULEDIR` environment variable into the `cog_modules_add_directory()` function, fix the bug that skipped using the environment variable when `cog_init()` is *not* used, and improve robustness:
- The path passed is checked to be a valid directory location.
- The environment variable is checked only once for the whole execution of the process, the first time the function is called with a `NULL` argument.
- The path in the environment variable is checked for validity as well. A warning is produced for invalid locations.
- If either the environment variable or the compiled-in default path are used, it is considered that the “default” path was set, and will not be set again to avoid re-scanning directories unnecessarily.
While at it, sprinkle comments on the code to …
> core: Make cog_modules_add_directory() honor COG_MODULEDIR

- core/cog-platform.c
- docs/running.md
- examples/viewport.c
- launcher/cog-launcher.c
Change `cog_platform_setup()` to allow passing `NULL` as the parameters string, and fall back to using the value of the `COG_PLATFORM_PARAMS` environment variable in that case. In order to keep the same ABI with existing platform plug-ins, the function ensures that an empty string is always passed when needed.
This change simplifies call sites for the function, which no longer need to handle reading the environment variable themselves, nor taking care of always passing a valid string, even if empty.
While at it, write the missing documentation for `cog_platform_setup()`.
----
This depends on https://github.com/Igalia/cog/pull/655
> core: Allow passing NULL as platform setup params

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.c
- platform/wayland/cog-utils-wl.h
- platform/wayland/cog-viewport-wl.c
**motivation:** Every single wl_surface in the Cog apps belongs to a specific Viewport but there is not a way, right now, in the code to know where     is the Viewport associated to the wl_surface.
**excerpt:** This change allows a direct way for accessing to the Viewport associated from a given wl_surface. Also opens the possibility of     to handle the input events methods avoiding this assumption: There is     just one single and unique CogView associated to the platform. This change is much more logical than the previous assumption.
> wl: Attach Viewport to the surface

- core/cog-view-private.h
- core/cog-view.c
- core/cog-view.h
- core/cog-viewport.c
- platform/wayland/cog-view-wl.c
- platform/wayland/cog-viewport-wl.c
Added a convenient reference to make explicit an **bidirectional the relationship between the CogViewport and the CogView**. This makes explicit the relation of membership of the a View respect the Viewport and breaks up the assumption of 'just one viewport in use' in the Platform. 
Also the WL plugin start to use the `cog_view_get_viewport()` to get the View's Viewport. This allows to use the CogViewport assigned to the CogView instead of the global CogViewport assigned to the Platform.
> Add in CogView a reference to the CogViewport where it belongs

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-platform-wl.h
- platform/wayland/cog-utils-wl.c
- platform/wayland/cog-utils-wl.h
- platform/wayland/cog-view-wl.c
Change the `cog_wl_platform_popup_create()` signature. It receives the viewport as it needs the information from the active viewport to get the wl_surface.
The viewport used by ` on_show_option_menu()` will be the one associated to the View.
> wl: Change cog_wl_platform_popup_* API

- platform/wayland/cog-view-wl.c
This fix a build error if the wayland-cursor dependency is not satisfied.
> wl: Fix scope of the COG_USE_WAYLAND_CURSOR ifdef for the on_mouse_target_changed handler

- core/cog-view.c
Remove the `G_PARAM_CONSTRUCT` flag from the `CogView.viewport` property, because it it supposed to be only readable and it the viewport is set in a separate step separate from view construction by using `cog_viewport_add()`. It would be technically possible to allow setting the viewport at construction time, but that would need some additional support code it would use `G_PARAM_CONSTRUCT_ONLY`. For now it is easier to remove the flag.
> core: Make the CogView.viewport property only readable

- platform/x11/cog-platform-x11.c
Only set the cursor when the resolved cursor is _not_ `XCB_CURSOR_NONE`.
> x11: Do not attempt to set an invalid cursor

- platform/wayland/cog-platform-wl.c
... on pointer_on_enter, touch_on_down and keyboard_on_enter.
It can be possible a situation during the destruction of a CogView where the UI-process were receiving and trying to process an input event for a non existant wl_surface.
Under this scenario, the wl_surface associated could be not longer accesible so the input handler will receive a null-pointer (0x0).
Backtrace:
```
0  0xb9999999 in wl_proxy_get_user_data (proxy=proxy@entry=0x0)
at ../wayland/src/wayland-client.c:2135
at /usr/include/wayland-client-protocol.h:3393
fixed_x=0, fixed_y=5, surface=0x0 <<<< , data=0xa9999999)
```
> wl: Check wl_surface before use it

- core/cog-view.c
- core/cog-view.h
Add convenient accessors to the "visible" property the to the **CogView** external API:
* `CogView::cog_view_set_visible()` sets the view as the one visible inside of the viewport where the view is attached.
* `CogView::cog_view_is_visible()` gets if the view is visible inside of the viewport where the view is attached.
> Add CogView::cog_view_[set|is]_visible() accessors

- core/cog-platform.c
- core/cog-platform.h
- core/cog-viewport.c
- launcher/cog-launcher.c
- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.c
- platform/wayland/cog-utils-wl.h
The input method context is now defined and assigned to the View once this is added to a **Viewport**, in `cog_viewport_add()`. It is not possible before because we need to have access to the `wl_surface` associated to the Viewport->Window for configuring the IM context.
> wl: Change IM context functions signature

- platform/wayland/cog-viewport-wl.c
The `COG_PLATFORM_WL_VIEW_FULLSCREEN` is evaluated during inside of the `cog_wl_viewport_create_window()`. At that point there is not yet a view created in the viewport associated to the window.
Allow the shells to set the fullscreen mode even if there is not a view available in the viewport. This will make the new views being created in fullscreen mode. This applies also to the one created during the initialization.
> wl: Fix the COG_PLATFORM_WL_VIEW_FULLSCREEN not works

- .gitignore
- meson.build
- meson_options.txt
- platform/x11/cog-platform-x11.c
- platform/x11/meson.build
- subprojects/packagefiles/xcb-util-keysyms-0.4.1/meson.build
- subprojects/xcb-keysyms.wrap
These patch set pulls the parts of the code from #303 which implement usage of `xcb-keysyms` to handle keyboard input event translation, adding a few niceties on top:
- Allow passing `-Dx11_keyboard=` to Meson to choose which methods are supported. It is possible to use `xkb`, `xcb-keysyms`, or both. Passing an empty list disables keyboard input to web views.
- If support for both XKB and `xcb-keysyms`, then XKB will be preferred, and if not available then `xcb-keysyms` is used as fallback.
- Lastly, add a Wrap subproject definition that teaches Meson how to download a tarball and build a static `xcb-keysyms` library when not available. The library is a single `.c` file so it does not add much weight to the X11 platform plug-in, and we make it less likely that people may end up without …
> x11: Support xcb-keysyms as fallback when XKB support not available

- platform/drm/cog-platform-drm.c
`find_crtc_for_encoder()` should not only check the bitmask but also the ID of the CRTC.
See #614 for a detailed description of the issue that this PR fixes.
> REGRESSION(47dee03): Broke DRM plugin on RPi4 (#614)

- launcher/cog-launcher.c
Add support for toggling WebKit runtime features using the WebKitFeature API introduced in version 2.42, by means of a `--features`/`-F` command line flag.
> launcher: Support toggling WebKit runtime features

- examples/viewport.c
- examples/viewports.c
Add calls to `cog_init()` to make the examples honor the `COG_PLATFORM_NAME`, `COG_PLATFORM_PARAMS`, and `COG_MODULEDIR` environment variables properly. While at it, fix their calls to `g_set_prgname()`.
> examples: Fix program names and call cog_init()

- .clang-tidy
Add a (for now) very simple configuration for `clang-tidy` that silences warnings about `sizeof()` expressions from `g_clear_{object,pointer}` macros. The `clang-tidy` configuration file is also used by `clangd`, so this also avoids these false positive diagnostics when using it in an editor with LSP support.
> clang-tidy: Add option to silence GLib macro warnings

- core/cog-platform-private.h
- core/cog-platform.c
- core/cog-platform.h
- core/cog-viewport.c
- platform/headless/cog-platform-headless.c
- platform/wayland/cog-platform-wl.c
Platform implementations may need (or want) to track all the `CogViewport` instances in use. Until now this was done by fetching the list of viewports from `CogShell`, but that assumed that a.) there is always a shell instantiated, and b.) there will ever be only one viewport. It is already possible _today_ to use multiple viewports (see `examples/viewports.c`) so the latter does not hold true. We want to also avoid using the shell from platform implementations so what this PR does is:
- Add two vfuncs `CogPlatform.viewport_created` and `CogPlatform.viewport_disposed`, and corresponding signals `CogPlatform::viewport-created` and `CogPlatform::viewport-disposed`. These are triggered from `CogViewport` during creation and disposal using private functions.
- Add multiple view support to the …
> core, wl, headless: New virtual functions in CogPlatform to track live viewport instances

- core/cog-shell.c
- core/cog-shell.h
- examples/viewport.c
- examples/viewports.c
- launcher/cog-launcher.c
Remove handling of viewports and views from `CogShell`. Tracking live viewports can be done using `CogPlatform` since #683 and platform plug-ins no longer depend on `CogShell` for that. The following are no longer needed in `CogShell`:
- The `:web-view` and `:viewport` properties, and their accessors.
- The `::create-view` and `::create-viewport` signals.
- The `.create_view()` virtual function and its default implementation.
- The `cog_shell_add_viewport()`, `cog_shell_remove_viewport()`, `cog_shell_get_n_viewports()`, and `cog_shell_get_nth_viewport()` methods.
As a side effect of the above removals, the examples have been changed to have them create their views using `cog_view_new()` instead of relying on the default implementation of the `CogShell.create_view()` virtual function.
The …
> core: Remove view and viewport handling from CogShell

- platform/wayland/cog-utils-wl.c
We have to check if the seat->pointer_obj is not set NULL. In certain Wayland environments we could have no pointer capabilities (WL_SEAT_CAPABILITY_POINTER). Under this scenario, the pointer_obj is not initialized.
Fixes #690.
> wl: Add pointer_obj safe-guard in cog_wl_seat_set_cursor()

- platform/gtk4/cog-platform-gtk4.c
`GtkGestureClick` and `GtkEventControllerMotion` provide `x` and `y` in widget allocation coordinates.
We must multiply them by the widget's scale factor when creating point events for WebKit.
Fixes #654
> gtk4: Incorporate scale factor into pointer events

- platform/drm/cog-drm-modeset-renderer.c
- platform/drm/cog-platform-drm.c
Use `drmGetCap()` in the DRM modesetting renderer to detect whether framebuffers can be created with modifiers, instead of always trying to use them and falling back to avoid them.
> drm: Detect if drivers support buffer modifiers

- launcher/cog-launcher.c
The view created for automation was not being saved in the viewport, leaving some required signals unhandled, like "close". This causes the view to never be destroyed when called from WebKit's WebPageProxy::close(), leading to infinite loop in the close window WebDriver algorithm, as the list of open windows would never change.
After hooking the close signal, there was the issue with cog_viewport_add ref'ing the view when storing the view with g_ptr_array_add but not releasing this reference when removing, doing just a ref/unref pair to preserve during the removal.
This commit removes the extra g_object_ref during the cleanup, effectively relying on the previously saved ref before unref'ing it
This should fix the WPT webdriver fixtures that rely on creating and destroying views for …
> automation: Save automated view and avoid dangling ref when closing window

- platform/wayland/cog-popup-menu-wl.c
When HTML select had 6 or 7 options those respective options were not rendered, they still functioned fine just not visible.
Before:
After:
> wl: Fix popup menu item 6 & 7 not rendering

- platform/wayland/meson.build
Weston 13 was released recently and the weston development branch is now using libweston-14-protocols.
> Add support for weston 14 protocols

- platform/wayland/cog-platform-wl.c
In some compositors it could be possible these 2 cases:
* to receive touch up/motion events immediately after a touch up (touch deinit the touch target).
* to receive pointer motion/leave event immediately after a touch leave (deinit the touch target).
This patch adds safeguards in the touch events callbacks
> wl: Add safe-guards for touch and pointer events

- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-utils-wl.h
- platform/wayland/cog-viewport-wl.c
- platform/wayland/meson.build
Ask compositors that support the `zxdg_decoration_manager_v1_interface` protocol to provide server-side decorations (SSD). This way it is more likely that the Cog surfaces will have window decorations. Note that compositors will still hide the decorations of fullscreen surfaces, but maximized ones will keep them, and this is the expected behaviour. Tested on Sway and Labwc, and should work in most (if not all) wlroots based compositors.
> wl: Prefer SSD via zxdg_decoration_manager_v1

- platform/wayland/cog-viewport-wl.c
Cast `CogWlViewport` to the correct `CogViewport` type before passing it alont to `cog_viewport_get_visible_view()`.
> wl: Fix compiler warning due to missing cast

- platform/wayland/cog-viewport-wl.c
Using the xdg-compositor protocol on a compositor that doesn't support it produces a segfault. Guard against this.
> wl: Only use xdg-decoration if it's supported by the compositor

- platform/gtk4/cog-platform-gtk4.c
Without the `wpe_view_activity_state_focused` flag, gamepad events aren't forwarded to the view.
This change is aligned with what is done in GTK port [1].
[1] https://commits.webkit.org/273882@main.
> gtk4: set focused activity state based on window::is-active

- launcher/cog-launcher.c
Make sure shell config-file parameter is set before setting up platform because it is used by the paltform to read the initial options.
> Fix setting platform options via configuration file

- platform/wayland/cog-platform-wl.c
> wl: Specify button modifier in listeners

- core/cog-view.c
- core/cog-view.h
- platform/wayland/cog-platform-wl.c
- platform/wayland/cog-view-wl.c
Move view fullscreening to a new vfunc in the `CogView` class, which gets in turn implemented by `CogWlView`. This moves the entry point to common code, which would allow other platform plug-ins to implement the functionality if desired. Also, handling its key binding can be moved along to common code.
> core, wl: Factor out view fullscreening

- platform/wayland/cog-platform-wl.c
On a multitouch screen, when several fingers are on the screen at the same time, if we set to null surface and target on touch_on_up() then we stop all the ongoing touch gestures and not only the one of the finger that caused the up event. That is becasue touch_on_motion() will refuse to process further events if surface or target are null.
Instead of doing that do not set to null this pointers on the touch_on_up() event. The value of those will be set again on the next touch_on_down() event in any case.
Related: https://github.com/Igalia/cog/issues/698
Related: https://bugs.webkit.org/show_bug.cgi?id=270516
> wl: do not set to null the surface and target at touch_on_up()

- meson.build
- meson_options.txt
This allows disabling libmanette support when libmanette is installed.
> build: make libmanette support explicit

- platform/wayland/cog-platform-wl.c
Key repeat rate must be converted from keys/second to a period to schedule the repeat timer.
> wl: fix key repeat timeout

- platform/wayland/meson.build
Weston 14 was released recently and the weston development branch is now using libweston-15-protocols.
> Add support for weston 15 protocols

- launcher/cog-launcher.c
Pick the `GOptionGroup` with JSC options provided by WebKit and add expose it to the command line parser.
> launcher: Add JSC command line options group

- .github/workflows/ci-native.yml
- .github/workflows/codestyle.yml
Use version 4 of `actions/upload-artifact`, as v3 has been deprecated and removed.
> CI: Use actions/upload-artifact v4

- docs/cog.toml.in
- docs/meson.build
Replace `@LIBSOUP_API@` in the `cog.toml.in` template with the libsoup API version being used, and update the URL to use `libsoup.gnome.org`
> docs: Use a versioned libsoup documentation URL

- data/depfile.py
- docs/meson.build
Convert the output from `gi-docgen gen-deps`, which is a list of files ingested to generate the documentation, into a format suitable to be read by Ninja (a Make snippet), and use it as the  `depfile` for the documentation custom target. The transformation is done using a small Python script, which does not introduce any new dependency because `gi-docgen` itself already required Python to be present.
> meson: Use a generated depfile for gi-docgen

- launcher/cog-launcher.c
On system dbus connection, the appid passed to the launcher was not taken into consideration yet, so taking the default id. This made it impossible to address multiple browser instances on the system bus. I moved the call to a place where we can take the appid. The end user is still responsible for creating the correct policy file!
Fixes:
https://github.com/Igalia/cog/issues/474
> cog-launcher: fix system dbus appid connection
