Igalia/cog

cog.c

This adds a new ``--platform`/`-P` command line flag which allows specifying the name of the platform plug-in to be loaded. If none is specified, a fall-back to the default WPE backend is used, which allows usage of e.g. [WPEBackend-rdk](https://github.com/WebPlatformForEmbedded/WPEBackend-rdk) and others.
This also adds a few `g_debug()` calls sprinkled here and there. This makes it easier to figure out which WPE backend is being used, and contributes a bit to fix issue #1.
----
Tested successfully with WPEBackend-rdk and WPEBackend-fdo (passing `--platform=fdo` for the latter).

Un-hardcode usage of FDO the platform module

---

platform/cog-platform-fdo.c

Using the API to retrieve the singleton avoids needing to keep a reference to it in in a static variable. Also, this makes it possible to retrieve the `WebKitWebView` to handle the keybindings.
Fixes #20

fdo: Use cog_launcher_get_default() to access the global singleton

---

platform/cog-platform-fdo.c

Use the established and documented process of dispatching Wayland event loop events via GSource facilities.

cog-platform-fdo: improve wl dispatches.

---

platform/cog-platform-fdo.c

It should have been removed as part of the patch removed blitting in favor of wrapping the EGL image in a wl_buffer <git~e9a306dcd>.

fdo: Remove unused code left behind my mistake

---

cogctl.c

cogctl: Fix uninitialized loop control variable

---

cog.c

See https://bugs.webkit.org/show_bug.cgi?id=150303

gtk: Workaround for WebKitGTK+ bug #150303

---

platform/cog-platform-fdo.c

Maximizing the surface asks the compositor to let it occupy as much as it would allow, e.g. without covering other important UI elements. This is toggled with the `COG_PLATFORM_FDO_VIEW_MAXIMIZE` environment variable. Note if both fullscreening *and* maximization are requested (using their respective environment variables) then fullscreening is preferred.

fdo: Support maximizing the Wayland surface

---

core/cog-utils.c

Change the `cog_uri_guess_from_user_input()` function slightly, so if an input URI is valid and the scheme refers to a network protocol, use the passed string directly, decoded from the command line locale. This avoids converting the `SoupURI` resulting from parsing to a string, which is what caused passwords in URIs to be stripped out.
Fixes #75

core: When guess input URIs, directly use valid ones

---

core/cogcore.pc.in

Fix wpe-webkit version (0.1 to 1.0) in cog/core/cogcore.pc.in (fixes issue #92)

Fix wpe-webkit version (0.1 to 1.0)

---

platform/cog-platform-fdo.c

Use `wpe_view_backend_dispatch_set_device_scale_factor()` only when compiling against a version of libwpe equal or newer than 1.3.0, which was the one introducing the new API.
The `wl_data.current_output.scale` member is set to `1` by default to avoid needing to guard every single usage of it. The value is set with a C99 designated  initializer, which guarantees that the rest of struct members are zeroed and allows removing a call to `memset()`.

fdo: Use device scale API only when available in libwpe

---

cmake/FindWaylandProtocols.cmake

in ... Method 1: If -DWAYLAND_PROTOCOLS=...

Fix Find WAYLAND_PROTOCOLS

---

CMakeLists.txt
platform/cog-platform-fdo.c

Please, pick this for 0.3 as well.

Improve logging to aid debugging when needed

---

cog.c

cog: New runtime CLI option for WebExtensions directory configuration

---

.travis.yml

This should speed up builds a bit further.

CI: Enable saving ccache and APT caches

---

CMakeLists.txt
platform/cog-platform-drm.c

Primarily initial input support, along with some misc stuff.

drm-experimental platform updates

---

modules/cog-fdo-shell.c

Since the FDO backend, wayland, etc. can fail to initialize
it makes sense to have the module implement the GInitable
interface. For now, the initable interface only tries to
load the fdo module.

cog-fdo-shell: Implement the GInitable interface

---

platform/cog-platform-fdo.c

Have the wl_pointer.axis() event gather 2D delta information. If possible,
the data is gathered and dispatch on the wl_pointer.frame() event,
otherwise immediately inside wl_pointer.axis().
When dispatching axis events, if the new 2D axis API is available and if the
underlying WebKit version is recent enough, the axis change is dispatched
through the wpe_input_axis_2d_event structure.
If that's not the case, the 2D movement is mimicked by dispatching for each
changed axis.

Support 2D scrolling via axis events

---

platform/cog-platform-fdo.c

Set only the opaque region for the `wl_surface` used as output the first time a `wl_buffer` is attached, and only once after the surface has been reconfigured, instead of doing it woth every frame.
This improves graphics intensive benchmarks. For example, with this change MotionMark results consistently improve between 6 and 7 points on a laptop with a Core i7-6600U at 2.6GHz and an Intel HD Graphics 520 GPU.

fdo: Avoid repeatedly setting opaque regions

---

platform/cog-platform-fdo.c

Reworks the fullscreen shell handling to respect the environment
variables COG_PLATFORM_FDO_VIEW_{WIDTH,HEIGHT} to set the backend
resolution, or COG_PLATFORM_FDO_VIEW_FULLSCREEN, which will make cog
resize to match the size of the largest connected output.

fdo: Handle sizing with fullscreen shell

---

platform/cog-platform-drm.c

Func keys like shift were completely ignored, which made it impossible to type capital letters or special characters.
I basically just copied the logic from wpebackend-rdk where it works as expected:
https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/8e35a98627361898059cc8212e5bc87993a57e0d/src/input/Libinput/LibinputServer.cpp#L84

drm: fix keyboard typing with shift and other func keys

---

platform/cog-platform-drm.c

DRM debug output

---

platform/cog-platform-drm.c

Default to atomic modesetting, if the capability is detected as usable.
It can be force-disabled through the 'disable-atomic-modesetting=true'
configuration setting under the 'drm' group in the provided config
key-value file.
Additionally to connector and CRTC objects, we now also search through
the planes, picking the primary plane as desired for presentation.
Necessary property information for all these objects is also gathered.
When committing the framebuffer object, in case of using atomic
modesetting, an atomic request is built, enhanced with all the relevant
properties. Once committed, a page flip event is expected and handled
the same way as with the non-atomic modesetting.

drm: add support for atomic modesetting

---

platform/cog-platform-drm.c

inspired by wpebackend-rdk https://github.com/WebPlatformForEmbedded/WPEBackend-rdk/blob/master/src/input/Libinput/KeyboardEventRepeating.cpp

drm: implement keyboard event repeating when the key remains pressed

---

core/cog-directory-files-handler.c

Return early from `cog_directory_files_handler_run()` if the calculated path to the location of the resource on disk happens to not be a descendant of the base path.

core: Ensure that files URI handler does not escape the base path

---

core/cog-view.c

Signed-off-by: Pablo Saavedra <psaavedra@igalia.com>

Remove default about:blank load action in the  View constructor

---

platform/drm/cog-platform-drm.c

Check for a recent-enough libwpebackend-fdo build dependency
and use the SHM export API and handling logic accordingly.

drm: add necessary guards for SHM export handling

---

.github/workflows/codestyle.yml

Fix code style checker CI action

---

core/cog-shell.c
docs/platform-drm.md

drm: Document configuration file options

---

CONTRIBUTING.md
docs/cog.toml.in
docs/contributing.md

Rework and improve some parts of the `CONTRIBUTING.md` document. As a bonus, add a symlink into `docs/` to have it included as one of the static pages of the manual generated by `gi-docgen`.

docs: Improve CONTRIBUTING.md, add to the manual

---

platform/gtk4/cog-platform-gtk4.c

Fixes https://github.com/Igalia/cog/issues/287

Implement fullscreen in GTK4 platform

---

CMakeLists.txt
hooks/pre-commit

Nasahdev format style

---

.github/workflows/ci-native.yml

CI: Make native build also use libwpe from Git

---

cog.c

This update fixes the only deprecation warning I saw when the application was built. Please let me know if there are others.

Nasahdev deprecation

---

.github/workflows/ci-cross.yml
.github/workflows/ci-native.yml

CI: Trigger build actions for merge requests

---

platform/drm/cog-platform-drm.c

Don't perform the complete DRM initialization to test whether the DRM module can
be used, instead only iterate through the retrieved DRM devices and indicate as
supported if a primary DRM node was detected.

drm: simplify the check-if-supported operation

---

docs/platform-wl.md

Document the environment variables honored by the Wayland platform plug-in.

wl: Document supported environment variables

---

docs/platform-wl.md

wl: Document available key bindings

---

platform/x11/cog-platform-x11.c

Implement setting view activity state flags, which allows WebKit to perform certain optimizations (like skipping updates while the view is not present in a window, or not visible) and makes certain features work as expected (like the Page Visibility API).
- Events `XCB_FOCUS_{IN,OUT}` modify `wpe_view_activity_state_focused`.
- Events `XCB_{UN,}MAP_NOTIFY` modify `wpe_view_activity_state_in_window`.
- Event `XCB_VISIBILITY_NOTIFY` modifies `wpe_view_activity_state_visible`; both partially obscured and completely unobscured windows are set as visible.
The corresponding event masks are added during window creation.
Interestingly, at least on GNOME Shell in an X11 session, Cog does not get any `XCB_VISIBILITY_NOTIFY` events after the initial one, even if the window is hidden iconified. This …

x11: Support setting view activity state flags

---

platform/x11/cog-platform-x11.c

Handle X11 expose events, which was missing. Typically composited environments (running `xcompmgr`, a composited desktop like GNOME Shell, or similar) never produces expose events: the compositor will keep around a buffer with the latest contents of the X11 windows, in order to perform composition, which means that it does not ever need to request application to repaint windows. Given that composited environment are common these days, that is likely the reason why this issue has not been
noticed earlier.
On the other hand, with more “traditional”, non-composited window managers will happily discard pixmaps for obscured windows (in order to save memory, for example) and rely on the fact that X11 applications are expected to repaint themselves when requested via expose events. In order to …

x11: Fix glitches in non-composited window managers

---

platform/common/cog-gl-utils.c
platform/common/cog-gl-utils.h
platform/gtk4/cog-platform-gtk4.c

A proposal to make work cog (tested only for gtk4 platform) with OpenGL4. In theory they are also compatible with OpenGL3.

Fix OpenGL4

---

platform/drm/cog-platform-drm.c
platform/gtk4/cog-platform-gtk4.c
platform/wayland/cog-platform-wl.c

Add target refresh rate reporting to drm, gtk4 and wayland backends. The
latter two should follow refresh rate/monitor changes, drm doesn't as
we're responsible for setting the mode and only ever set it once.

Add target refresh rate reporting

---

platform/x11/cog-platform-x11.c

Fixes #391
Steps to test:
1. Run COG_MODULEDIR=$(pwd)/modules ./cog -P x11 'data:text/html,<input>'
2. Enter various key combinations (with shift, control, caps lock, num lock, etc), and verify that they work.
What was missing was updating the xkb state on each key press.
That needs to be done before the call to xkb_state_key_get_one_sym
as xkb reads the state in order to determine which keysym it should
output.
The function is more complex that in need to be because XCB, X11,
and WPE all use different masks for the modifiers.
Future improvements to this code might include:
* unifying xcb_handle_key_press and xcb_handle_key_release
* handle xkb keyboard map changes
* handle AltGr

x11: handle upper case letter, caps lock, num lock, control and alt

---

platform/drm/cog-platform-drm.c
platform/wayland/cog-im-context-wl-v1.c

Issue: https://github.com/Igalia/cog/issues/449
Fixes https://github.com/Igalia/cog/issues/449 for master

Fix missing xkbcommon.h include

---

platform/wayland/cog-platform-wl.c

Fix fullscreen shm buffer dimensions

---

meson.build

Following upstream WPE changes in https://github.com/WebKit/WebKit/pull/3886

Bump WPE WebKit dependency from 1.1 to 2.0

---

platform/drm/cog-platform-drm.c
platform/drm/meson.build

While testing cog in RPI4 I got these warnings.

DRM platform fixes

---

platform/wayland/cog-platform-wl.c

Fixed uninitialized wl_shm for cursor

---

platform/gtk4/cog-platform-gtk4.c

We're now tracking `GtkGLArea`'s scale factor and passing it to the backend every time it changes.

gtk4: React on device scale factor changes.

---

platform/wayland/cog-platform-wl.c

Skip frames which do not match the size of the output surface, in order to avoid a Wayland protocol error resulting from mismatched sizes. This can happen, for example, after requesting that the surface is maximized, while the view backend has already produced some frames, but the change of size has not been yet noted by WebKit. In these cases we can safely skip using the frames but they  still need to be ACK'd in order to let WebKit continue producing new ones, which eventually will arrive in the desired size.
Related issue #537

wl: Do not attach frames with invalid size to the surface

---

.github/toolchain.sh
.github/workflows/ci-cross.yml
.github/workflows/ci-native.yml
.github/workflows/codestyle.yml

Update versions of actions to the latest. Fix retry download if checksum mismatches the expected one.

CI: Miscellaneous improvements

---

platform/headless/cog-platform-headless.c

Tidy up the headless backend in preparation for adding multiple view support down the line. In particular, rename `struct platform_window` to `CogHeadlessView`, and embed an instance in the `CogPlatform` struct for now, removing the `win` global.
While at it, remove the `view_backend` member from `CogHeadlessView`, because once it is returned from the `get_view_backend` vfunc the ownership is transferred anyway, and it is not needed elsewhere.
Rename `setup_fdo_exportable` to `cog_headless_view_initialize`, and leave out the wpe-fdo initialization in `cog_headless_platform_setup`. Add a matching `cog_headless_view_finalize`, which takes care of disarming the tick timer. Destroying the view backend is now done using the `destroy_notify` callback from `WebKitWebViewBackend`, which is more …

headless: Cleanup in preparation for multiple view support

---

launcher/cog-launcher.c

Remove the unneeded instance variable that tracks the current platform in `CogLauncher`, instead use the default global `CogPlatform` which has been around since a3815bb.

launcher: Simplify by using global CogPlatform

---

platform/headless/cog-platform-headless.c

Move the variable for the frame tick source into `CogHeadlessPlatform`; there is no reason for it to be part of the `CogHeadlessView` type. Moreover, once multiple views are supported, it would be better to have a single timer to update all of them at once, instead of a timer per view.

headless: Move frame tick source to platform object

---

platform/wayland/cog-platform-wl.c

Improve tracking of output properties and setting output scaling factor to avoid blurry rendering due to using 1x scaling factor on output that use 2x scaling (or higher). The main offender was a missing call to `wpe_view_backend_dispatch_set_device_scale_factor()` in `resize_window()`.
Instead of keeping only the scaling factor for for the Wayland surface, keep a reference to its current output device. The output is initially set to the first one reported by the Wayland compositor (which usually is the primary output), ensuring that the pointer is always valid. This allows setting fallback values for device output scaling and refresh rate in `output_handle_done()`. Combined, both changes allow keeping other code simple, as it can assume the values will always be valid.
Overall, this …

wl: fix blurry rendering in some compositors

---

launcher/cog-launcher.c

launcher: Add command-line option for controlling autoplay behavior

---

core/meson.build

Add missing cog-export.h header in the cogcore_headers

---

platform/wayland/cog-platform-wl.c
platform/wayland/cog-utils-wl.c
platform/wayland/cog-utils-wl.h

Change the fixed array of outputs and use instead a `wl_list`.

wl: Un-hardcode the fixed amount of outputs

---

platform/drm/cog-platform-drm.c

In addition to setting the logical input area size during initialization in `init_input()`, also update the size in `cog_drm_platform_set_property()`. The code that picks the correct dimensions depending on the rotation is moved into its own function and reused in both locations.
----
This is a follow-up to https://github.com/Igalia/cog/pull/554

drm: Update logical input area size on property changes

---

platform/wayland/cog-platform-wl.c

wl: Fix unused variable display warning

---

platform/wayland/cog-viewport-wl.c

... before call the cog_wl_platform_configure_geometry().
Unreviewed change.

wl: Check dimensions in cog_wl_viewport_resize_to_largest_output

---

docs/platform-drm.md

The docs stated that it accept a refresh rate which is not true

Fix documentation of COG_PLATFORM_DRM_VIDEO_MODE

---

.github/workflows/ci-cross.yml
.github/workflows/ci-native.yml
.github/workflows/codestyle.yml
data/check-style

CI: Update to latest actions version and base image
